### ISSUE TITLE
ImportError: cannot import name 'WagtailTranslationOptions'

### ISSUE THREAD

**Issue by SalahAdDin** [infoportugal/wagtail-modeltranslation#110]
Well, it is: Wrong import library.
```
from wagtail_modeltranslation.translation import WagtailTranslationOptions
from modeltranslation.decorators import register
```

Correct library is `from wagtail_modeltranslation.translator import WagtailTranslationOptions`.

But changing the library we get this error:
```bash
./manage.py migrate                                                                                           1 ↵  5403  12:03:05 
Traceback (most recent call last):
  File "./manage.py", line 12, in <module>
    execute_from_command_line(sys.argv)
  File "/home/salahaddin/Proyectos/uzman/lib/python3.6/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/home/salahaddin/Proyectos/uzman/lib/python3.6/site-packages/django/core/management/__init__.py", line 341, in execute
    django.setup()
  File "/home/salahaddin/Proyectos/uzman/lib/python3.6/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/salahaddin/Proyectos/uzman/lib/python3.6/site-packages/django/apps/registry.py", line 115, in populate
    app_config.ready()
  File "/home/salahaddin/Proyectos/uzman/lib/python3.6/site-packages/wagtail_modeltranslation/apps.py", line 18, in ready
    handle_translation_registrations()
  File "/home/salahaddin/Proyectos/uzman/lib/python3.6/site-packages/modeltranslation/models.py", line 81, in handle_translation_registrations
    autodiscover()
  File "/home/salahaddin/Proyectos/uzman/lib/python3.6/site-packages/modeltranslation/models.py", line 32, in autodiscover
    import_module(module)
  File "/home/salahaddin/Proyectos/uzman/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "/home/salahaddin/Proyectos/uzman/uzman/about/translation.py", line 1, in <module>
    from wagtail_modeltranslation import WagtailTranslationOptions
ImportError: cannot import name 'WagtailTranslationOptions'
 salahaddin@TulipanROG  ~/Proyectos/uzman/uzman   internationalization ● ? ↑23  (uzman)  ./manage.py migrate                                                                                           1 ↵  5403  12:03:15 
Traceback (most recent call last):
  File "./manage.py", line 12, in <module>
    execute_from_command_line(sys.argv)
  File "/home/salahaddin/Proyectos/uzman/lib/python3.6/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/home/salahaddin/Proyectos/uzman/lib/python3.6/site-packages/django/core/management/__init__.py", line 341, in execute
    django.setup()
  File "/home/salahaddin/Proyectos/uzman/lib/python3.6/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/salahaddin/Proyectos/uzman/lib/python3.6/site-packages/django/apps/registry.py", line 115, in populate
    app_config.ready()
  File "/home/salahaddin/Proyectos/uzman/lib/python3.6/site-packages/wagtail_modeltranslation/apps.py", line 18, in ready
    handle_translation_registrations()
  File "/home/salahaddin/Proyectos/uzman/lib/python3.6/site-packages/modeltranslation/models.py", line 81, in handle_translation_registrations
    autodiscover()
  File "/home/salahaddin/Proyectos/uzman/lib/python3.6/site-packages/modeltranslation/models.py", line 32, in autodiscover
    import_module(module)
  File "/home/salahaddin/Proyectos/uzman/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "/home/salahaddin/Proyectos/uzman/uzman/about/translation.py", line 26, in <module>
    class AboutPageTranslation(WagtailTranslationOptions):
  File "/home/salahaddin/Proyectos/uzman/lib/python3.6/site-packages/modeltranslation/decorators.py", line 23, in wrapper
    translator.register(model_or_iterable, opts_class, **options)
  File "/home/salahaddin/Proyectos/uzman/lib/python3.6/site-packages/modeltranslation/translator.py", line 457, in register
    self._register_single_model(model, opts)
  File "/home/salahaddin/Proyectos/uzman/lib/python3.6/site-packages/modeltranslation/translator.py", line 474, in _register_single_model
    add_translation_fields(model, opts)
  File "/home/salahaddin/Proyectos/uzman/lib/python3.6/site-packages/modeltranslation/translator.py", line 142, in add_translation_fields
    model=model, field_name=field_name, lang=l, empty_value=field_empty_value)
  File "/home/salahaddin/Proyectos/uzman/lib/python3.6/site-packages/modeltranslation/fields.py", line 70, in create_translation_field
    return translation_class(translated_field=field, language=lang, empty_value=empty_value)
  File "/home/salahaddin/Proyectos/uzman/lib/python3.6/site-packages/modeltranslation/fields.py", line 123, in __init__
    trans_opts = translator.get_options_for_model(self.model)
  File "/home/salahaddin/Proyectos/uzman/lib/python3.6/site-packages/modeltranslation/translator.py", line 621, in get_options_for_model
    'translation' % model.__name__)
modeltranslation.translator.NotRegistered: The model "Page" is not registered for translation
```

So, which is solution for this error?

**Comment by Alexandre27** [comment]
There was a typo in the docs, where it said `from wagtail_modeltranslation.translation import WagtailTranslationOptions` it should be `from wagtail_modeltranslation.translator import WagtailTranslationOptions`. The docs were already fixed.

**Comment by v1kku** [comment]
@Alexandre27 The typo isn't the issue here. The `NotRegistered` error is being raised after you change to the correct import.

**Comment by v1kku** [comment]
Nevermind, the error is raised when you don't add wagtail_modeltranslation `before all apps that you want to translate` as per the docs.
