### ISSUE TITLE
Copy content 

### ISSUE THREAD

**Issue by Erwhann-Rouge** [infoportugal/wagtail-modeltranslation#134]
The button that copy Streamfield content from a language to another language doesn't work when creating a new Page.

This is because the AJAX request tries to load existing fields from the database, and when creating a new page, there is no corresponding item stored in it.

**Comment by dmarcelino** [comment]
I'm experiencing the same issue using django v1.10, wagtail v1.6.3 and modeltranslation v0.12.1.

@DiogoMarques29, any chance you guys can take a look? Below is my stack trace:

```
Internal Server Error: /cms/pages/291/edit/copy_translation_content
Traceback (most recent call last):
  File "/home/dario/development/myproject/.venv/lib/python3.5/site-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/home/dario/development/myproject/.venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/dario/development/myproject/.venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3.5/contextlib.py", line 30, in inner
    return func(*args, **kwds)
  File "/home/dario/development/myproject/.venv/lib/python3.5/site-packages/django/views/decorators/cache.py", line 43, in _cache_controlled
    response = viewfunc(request, *args, **kw)
  File "/home/dario/development/myproject/.venv/lib/python3.5/site-packages/wagtail/wagtailadmin/decorators.py", line 24, in decorated_view
    return view_func(request, *args, **kwargs)
  File "/home/dario/development/myproject/.venv/lib/python3.5/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/dario/development/myproject/.venv/src/wagtail-modeltranslation/wagtail_modeltranslation/wagtail_hooks.py", line 80, in return_translation_target_field_rendered_html
    patched_item["value"] = att[1]
TypeError: 'NoneType' object does not support item assignment
ERROR 2017-11-30 17:00:41,523 exception 3972 139992471930624 Internal Server Error: /cms/pages/291/edit/copy_translation_content
Traceback (most recent call last):
  File "/home/dario/development/myproject/.venv/lib/python3.5/site-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/home/dario/development/myproject/.venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/dario/development/myproject/.venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3.5/contextlib.py", line 30, in inner
    return func(*args, **kwds)
  File "/home/dario/development/myproject/.venv/lib/python3.5/site-packages/django/views/decorators/cache.py", line 43, in _cache_controlled
    response = viewfunc(request, *args, **kw)
  File "/home/dario/development/myproject/.venv/lib/python3.5/site-packages/wagtail/wagtailadmin/decorators.py", line 24, in decorated_view
    return view_func(request, *args, **kwargs)
  File "/home/dario/development/myproject/.venv/lib/python3.5/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/dario/development/myproject/.venv/src/wagtail-modeltranslation/wagtail_modeltranslation/wagtail_hooks.py", line 80, in return_translation_target_field_rendered_html
    patched_item["value"] = att[1]
TypeError: 'NoneType' object does not support item assignment
[30/Nov/2017 17:00:41] "POST /cms/pages/291/edit/copy_translation_content HTTP/1.1" 500 24618
```


Thanks!

**Comment by pyMan** [comment]
See #96 and more specifically https://github.com/infoportugal/wagtail-modeltranslation/pull/96/commits/eb8dfadc0ceea5466a58745241ce2a3722190fb2

**Comment by akmiller01** [comment]
@dmarcelino, I think you're running into a separate, but related issue with how wagtail-modeltranslation deals with the content copy JSON. It appears to be anticipating a dictionary in the order '{"name": ... , "value" : ... }', but since the order of keys in dictionaries can be arbitrary, occasionally the "value" key comes first and the code attempts to assign "value" to a None type.

I've made a pull request here that initializes the trouble variable as a dictionary in the first place rather than a None type: https://github.com/infoportugal/wagtail-modeltranslation/pull/201
