### ISSUE TITLE
v0.6: ImproperlyConfigured: StreamField is not supported by modeltranslation

### ISSUE THREAD

**Issue by dmarcelino** [infoportugal/wagtail-modeltranslation#139]
Olá @DiogoMarques29, @Alexandre27,

I'm trying to add `wagtail-modeltranslation` v0.6 to an existing project but I can't seem to make it work. I always get: `ImproperlyConfigured: StreamField is not supported by modeltranslation`.

## Setup

models.py
```python
class BasePage(Page):
    body = StreamField([
        ('heading', blocks.CharBlock(classname="full title")),
        ('paragraph', blocks.RichTextBlock()),
        ('image', ImageChooserBlock()),
        ('table', TableBlock()),
        ('imagetable', ImageTableBlock()),
    ])

    content_panels = Page.content_panels + [
        StreamFieldPanel('body'),
    ]
```

translation.py
```python
from wagtail_modeltranslation.translator import WagtailTranslationOptions
from wagtail_modeltranslation.translation import register
from .models import BasePage

@register(BasePage)
class BasePageTranslationOptions(WagtailTranslationOptions):
    fields = ('body',)
```

settings.py
```python
INSTALLED_APPS = (
    ...
    'wagtail_modeltranslation',  # placed at the end. Putting it earlier did not change the outcome
 )

LANGUAGE_CODE = 'en'

LANGUAGES = (
    ('en', _('English')),
    ('pt', _('Portuguese')),
)

USE_I18N = True
```

Versions
```
django_modeltranslation: latest from development
wagtail_modeltranslation: tried both 0.6.0rc2 and latest
wagtail==1.6.3
django==1.10.2
```

## Stacktrace

```
(.venv) dario@ubuntu-VBox:~/development/myproject$ python manage.py makemigrations
Traceback (most recent call last):
  File "manage.py", line 23, in <module>
    execute_from_command_line(sys.argv)
  File "/home/dario/development/myproject/.venv/lib/python3.5/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/home/dario/development/myproject/.venv/lib/python3.5/site-packages/django/core/management/__init__.py", line 341, in execute
    django.setup()
  File "/home/dario/development/myproject/.venv/lib/python3.5/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/dario/development/myproject/.venv/lib/python3.5/site-packages/django/apps/registry.py", line 115, in populate
    app_config.ready()
  File "/home/dario/development/myproject/.venv/src/wagtail-modeltranslation/wagtail_modeltranslation/apps.py", line 18, in ready
    handle_translation_registrations()
  File "/home/dario/development/myproject/.venv/src/django-modeltranslation/modeltranslation/models.py", line 75, in handle_translation_registrations
    autodiscover()
  File "/home/dario/development/myproject/.venv/src/django-modeltranslation/modeltranslation/models.py", line 26, in autodiscover
    import_module(module)
  File "/home/dario/development/myproject/.venv/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/dario/development/myproject/myproject/cms/translation.py", line 7, in <module>
    class BasePageTranslationOptions(WagtailTranslationOptions):
  File "/home/dario/development/myproject/.venv/src/django-modeltranslation/modeltranslation/decorators.py", line 23, in wrapper
    translator.register(model_or_iterable, opts_class, **options)
  File "/home/dario/development/myproject/.venv/src/django-modeltranslation/modeltranslation/translator.py", line 478, in register
    self._register_single_model(model, opts)
  File "/home/dario/development/myproject/.venv/src/django-modeltranslation/modeltranslation/translator.py", line 495, in _register_single_model
    add_translation_fields(model, opts)
  File "/home/dario/development/myproject/.venv/src/django-modeltranslation/modeltranslation/translator.py", line 142, in add_translation_fields
    model=model, field_name=field_name, lang=l, empty_value=field_empty_value)
  File "/home/dario/development/myproject/.venv/src/django-modeltranslation/modeltranslation/fields.py", line 68, in create_translation_field
    '%s is not supported by modeltranslation.' % cls_name)
django.core.exceptions.ImproperlyConfigured: StreamField is not supported by modeltranslation.
```

I'm fairly confident about my i18n setup since I have both django's native translations working and also django-modeltranslation. I've tried removing django-modeltranslation from setting.py, I've tried playing with the apps' order in settings.py but nothing seems to help. Any ideas?

Obrigado

**Comment by dmarcelino** [comment]
Finally figured it out. After much playing with the apps orders I've finally reached the following:

```
    # django.contrib.* apps
    ...

    'wagtail_modeltranslation',  # i18n for wagtail (must come before modeltranslation)
    'modeltranslation',  # i18n for models

    # Admin
    'django.contrib.admin',

    # third party apps
    ...
```

Now everything works fine.

**Comment by Matu-sunuwawa** [comment]
okay that is nice but would you mind to share ideas about how it looks like the admins.py cuz am working like this project???
