### ISSUE TITLE
Translated fields not created in test database

### ISSUE THREAD

**Issue by jorenham** [infoportugal/wagtail-modeltranslation#175]
When I run my (previously working) Django unit tests, I get the following traceback

```Python traceback
Creating test database for alias 'default'...
Traceback (most recent call last):
  File "/project/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/project/lib/python3.5/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such column: wagtailcore_page.title_nl

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/pycharm-2017.2.1/helpers/pycharm/django_test_manage.py", line 168, in <module>
    utility.execute()
  File "/pycharm-2017.2.1/helpers/pycharm/django_test_manage.py", line 142, in execute
    _create_command().run_from_argv(self.argv)
  File "/project/lib/python3.5/site-packages/django/core/management/commands/test.py", line 29, in run_from_argv
    super(Command, self).run_from_argv(argv)
  File "/project/lib/python3.5/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/project/lib/python3.5/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/home/joren/Software/pycharm-2017.2.1/helpers/pycharm/django_test_manage.py", line 104, in handle
    failures = TestRunner(test_labels, **options)
  File "/home/joren/Software/pycharm-2017.2.1/helpers/pycharm/django_test_runner.py", line 255, in run_tests
    extra_tests=extra_tests, **options)
  File "/home/joren/Software/pycharm-2017.2.1/helpers/pycharm/django_test_runner.py", line 156, in run_tests
    return super(DjangoTeamcityTestRunner, self).run_tests(test_labels, extra_tests, **kwargs)
  File "/project/lib/python3.5/site-packages/django/test/runner.py", line 601, in run_tests
    old_config = self.setup_databases()
  File "/project/lib/python3.5/site-packages/django/test/runner.py", line 546, in setup_databases
    self.parallel, **kwargs
  File "/project/lib/python3.5/site-packages/django/test/utils.py", line 187, in setup_databases
    serialize=connection.settings_dict.get('TEST', {}).get('SERIALIZE', True),
  File "/project/lib/python3.5/site-packages/django/db/backends/base/creation.py", line 77, in create_test_db
    self.connection._test_serialized_contents = self.serialize_db_to_string()
  File "/project/lib/python3.5/site-packages/django/db/backends/base/creation.py", line 121, in serialize_db_to_string
    serializers.serialize("json", get_objects(), indent=None, stream=out)
  File "/project/lib/python3.5/site-packages/django/core/serializers/__init__.py", line 129, in serialize
    s.serialize(queryset, **options)
  File "/project/lib/python3.5/site-packages/django/core/serializers/base.py", line 80, in serialize
    for count, obj in enumerate(queryset, start=1):
  File "/project/lib/python3.5/site-packages/django/db/backends/base/creation.py", line 117, in get_objects
    for obj in queryset.iterator():
  File "/project/lib/python3.5/site-packages/django/db/models/query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch)
  File "/project/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 899, in execute_sql
    raise original_exception
  File "/project/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 889, in execute_sql
    cursor.execute(sql, params)
  File "/project/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/project/lib/python3.5/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/project/lib/python3.5/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/project/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/project/lib/python3.5/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such column: wagtailcore_page.title_nl

Process finished with exit code 1
```

**Comment by dmarcelino** [comment]
Sounds like you'll need to run `sync_page_translation_fields` command during test setup. Something like what's done in [wagtail_modeltranslation/tests/tests.py#L105](https://github.com/infoportugal/wagtail-modeltranslation/blob/master/wagtail_modeltranslation/tests/tests.py#L105):

```python
call_command('sync_page_translation_fields', interactive=False, verbosity=0, database=connections[DEFAULT_DB_ALIAS].alias)
```

Otherwise those columns won't be created.

**Comment by jorenham** [comment]
@dmarcelino Strangely that didn't solve it for me. I still get the same error.

**Comment by dmarcelino** [comment]
Hi @jorenham, please try the following:

1. 
```python
pip install -e git+https://github.com/dmarcelino/wagtail-modeltranslation.git@migrate#egg=wagtail-modeltranslation
```
2. In your test Django settings add `'wagtail_modeltranslation.migrate',` to `INSTALLED_APPS`.
3. Remove any programmatic call to `sync_page_translation_fields` if you still have it.

Explanation: the `migrate` branch you're installing from adds an override to Django's `migrate` command which runs `sync_page_translation_fields` immediately after. This fixed the issue for me.

**Comment by jorenham** [comment]
@dmarcelino That did it!

**Comment by dmarcelino** [comment]
I'm happy to hear that 🙂. I'll add some docs to that branch and submit a PR.

**Comment by dmarcelino** [comment]
@jorenham, @DiogoMarques29 and @Alexandre27 please review #178.

@DiogoMarques29, initially I was against adding a `migrate` command override but ended up doing it. I still think people should generally avoid it (so they know what's happening) but it's certainly the simpler solution for running tests.

**Comment by jorenham** [comment]
@dmarcelino What about something less obtrusive like the `post_migrate` signal? https://docs.djangoproject.com/en/dev/ref/signals/#post-migrate

**Comment by dmarcelino** [comment]
@jorenham, `post_migrate` should also work (it was actually one of the avenues I explored) but it has the disadvantage of not being optional, as in you wouldn't be able to run `migrate` without running `sync_page_translation_fields`, which is less than ideal. `sync_page_translation_fields` only needs to be ran when a new language is added which is less frequent than schema changes.

Having a nested app with a `migrate` command make things more versatile, keeping all options available to the developer.

Having said that, if you prefer to use the  `post_migrate` signal in your test setup, instead of adding `'wagtail_modeltranslation.migrate',` to your `INSTALLED_APPS`, that's certainly a valid scenario.

**Comment by jorenham** [comment]
@dmarcelino I like the `post_migrate` option better. You could add a setting to not use it. That way the user can still decide to opt-out and the solution is non-obtrusive

**Comment by dmarcelino** [comment]
@jorenham, in regards to data and doing things in ways that are not conventional (which unfortunately `wagtail-modeltranslation` has to do, see [caveats](http://wagtail-modeltranslation.readthedocs.io/en/latest/caveats.html)) it's preferable to play safe. Django's `migrate` is meant to apply migrations previously created by `makemigrations`, it's not meant to create translation fields using SQL introspection. It's generally not a good idea to mess with people's databases without them being aware of it. Even more so when changing a table that belongs to a 3rd party app (`Page` belongs to Wagtail).

PR #178 carries the underlying suggestion that if a user wants `migrate` to add translation fields to `Page`, then s/he can do it by knowingly and explicitly adding `'wagtail_modeltranslation.migrate',` to `INSTALLED_APPS`. IMO that's a reasonable trade-off between being conservative with other people's data and versatility.

**Comment by jorenham** [comment]
@dmarcelino Strangely in 0.9 the issue has resurfaced again (Django 1.11). Calling `sync_page_translation_fields` does not help either.

**Comment by DiogoMarques29** [comment]
Hello @jorenham 
do you have these on INSTALLED_APPS:

'wagtail_modeltranslation',
'wagtail_modeltranslation.makemigrations',
'wagtail_modeltranslation.migrate',

Cheers

**Comment by jorenham** [comment]
@DiogoMarques29 Yes all of them

**Comment by DiogoMarques29** [comment]
@jorenham can you show a traceback of the error?

**Comment by jorenham** [comment]
```
Traceback (most recent call last):
  File "/projects/lib/python3.5/site-packages/django/db/backends/utils.py", line 62, in execute
    return self.cursor.execute(sql)
  File "/projects/lib/python3.5/site-packages/django/db/backends/sqlite3/base.py", line 326, in execute
    return Database.Cursor.execute(self, query)
sqlite3.OperationalError: near "USING": syntax error

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/pycharm/helpers/pycharm/django_test_manage.py", line 168, in <module>
    utility.execute()
  File "/pycharm/helpers/pycharm/django_test_manage.py", line 142, in execute
    _create_command().run_from_argv(self.argv)
  File "/projects/lib/python3.5/site-packages/django/core/management/commands/test.py", line 29, in run_from_argv
    super(Command, self).run_from_argv(argv)
  File "/projects/lib/python3.5/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/projects/lib/python3.5/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/pycharm/helpers/pycharm/django_test_manage.py", line 104, in handle
    failures = TestRunner(test_labels, **options)
  File "/pycharm/helpers/pycharm/django_test_runner.py", line 255, in run_tests
    extra_tests=extra_tests, **options)
  File "/pycharm/helpers/pycharm/django_test_runner.py", line 156, in run_tests
    return super(DjangoTeamcityTestRunner, self).run_tests(test_labels, extra_tests, **kwargs)
  File "/projects/lib/python3.5/site-packages/django/test/runner.py", line 601, in run_tests
    old_config = self.setup_databases()
  File "/projects/lib/python3.5/site-packages/django/test/runner.py", line 546, in setup_databases
    self.parallel, **kwargs
  File "/projects/lib/python3.5/site-packages/django/test/utils.py", line 187, in setup_databases
    serialize=connection.settings_dict.get('TEST', {}).get('SERIALIZE', True),
  File "/projects/lib/python3.5/site-packages/django/db/backends/base/creation.py", line 69, in create_test_db
    run_syncdb=True,
  File "/projects/lib/python3.5/site-packages/django/core/management/__init__.py", line 131, in call_command
    return command.execute(*args, **defaults)
  File "/projects/lib/python3.5/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/projects/lib/python3.5/site-packages/wagtail_modeltranslation/management/commands/migrate_translation.py", line 25, in handle
    super(Command, self).handle(*args, **options)
  File "/projects/lib/python3.5/site-packages/django/core/management/commands/migrate.py", line 204, in handle
    fake_initial=fake_initial,
  File "/projects/lib/python3.5/site-packages/django/db/migrations/executor.py", line 115, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/projects/lib/python3.5/site-packages/django/db/migrations/executor.py", line 145, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/projects/lib/python3.5/site-packages/django/db/migrations/executor.py", line 244, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/projects/lib/python3.5/site-packages/django/db/migrations/migration.py", line 129, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/projects/lib/python3.5/site-packages/django/db/migrations/operations/special.py", line 108, in database_forwards
    self._run_sql(schema_editor, self.sql)
  File "/projects/lib/python3.5/site-packages/django/db/migrations/operations/special.py", line 133, in _run_sql
    schema_editor.execute(statement, params=None)
  File "/projects/lib/python3.5/site-packages/django/db/backends/base/schema.py", line 136, in execute
    cursor.execute(sql, params)
  File "/projects/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/projects/lib/python3.5/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/projects/lib/python3.5/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/projects/lib/python3.5/site-packages/django/db/backends/utils.py", line 62, in execute
    return self.cursor.execute(sql)
  File "/projects/lib/python3.5/site-packages/django/db/backends/sqlite3/base.py", line 326, in execute
    return Database.Cursor.execute(self, query)
django.db.utils.OperationalError: near "USING": syntax error
```

**Comment by DiogoMarques29** [comment]
This error is different from the first one. Something is wrong with the query being executed in sqlite3, I believe not related to wagtail-modeltranslation. Have you tried to run the tests without this app?

**Comment by jorenham** [comment]
@DiogoMarques29 Yes you're right, I blindly assumed it was the same error but the're seems to be an error in my data. Thanx for the help!
