### ISSUE TITLE
modeltranslation.translator.DescendantRegistered

### ISSUE THREAD

**Issue by stuaxo** [infoportugal/wagtail-modeltranslation#182]
Hi,
   I'm adding wagtail modeltranslation to an existing project,

I go this message though -

```
modeltranslation.translator.DescendantRegistered: Model "Page" cannot be registered after its subclass "SectorPage"
```

Any idea whats going on and how to fix it ?

**Comment by stuaxo** [comment]
Here's the stack trace -   I've added a translation.py for ```SectorPage```

```
$  python manage.py 
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/stu/.virtualenvs/dit-invest/lib/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/home/stu/.virtualenvs/dit-invest/lib/python3.6/site-packages/django/core/management/__init__.py", line 338, in execute
    django.setup()
  File "/home/stu/.virtualenvs/dit-invest/lib/python3.6/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/stu/.virtualenvs/dit-invest/lib/python3.6/site-packages/django/apps/registry.py", line 116, in populate
    app_config.ready()
  File "/home/stu/projects/external/wagtail-modeltranslation/wagtail_modeltranslation/apps.py", line 18, in ready
    handle_translation_registrations()
  File "/home/stu/projects/external/django-modeltranslation/modeltranslation/models.py", line 75, in handle_translation_registrations
    autodiscover()
  File "/home/stu/projects/external/django-modeltranslation/modeltranslation/models.py", line 26, in autodiscover
    import_module(module)
  File "/home/stu/.virtualenvs/dit-invest/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/stu/projects/external/wagtail-modeltranslation/wagtail_modeltranslation/translation.py", line 11, in <module>
    class PageTR(TranslationOptions):
  File "/home/stu/projects/external/django-modeltranslation/modeltranslation/decorators.py", line 23, in wrapper
    translator.register(model_or_iterable, opts_class, **options)
  File "/home/stu/projects/external/django-modeltranslation/modeltranslation/translator.py", line 472, in register
    ' "%s"' % (model.__name__, descendants[0]))
modeltranslation.translator.DescendantRegistered: Model "Page" cannot be registered after its subclass "SectorPage"

```

**Comment by stuaxo** [comment]
So - I just needed to put wagtail modeltranslations as the first entry in INSTALLED_APPS, before my apps.

I guess maybe the error message could have a bit more info, but will close this for now.
