### ISSUE TITLE
No Page extending models can be left without translation

### ISSUE THREAD

**Issue by kdkocev** [infoportugal/wagtail-modeltranslation#196]
In some projects not all models that extend `Page` should be translated.
In 0.6.0rc1 everything worked fine.
When I migrated to wagtail-modeltranslation 0.8.0 I got the following exception when running the project.
```
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7f0828994950>
Traceback (most recent call last):
  File "/home/user/code/hacksoft/env/project/lib/python3.6/site-packages/django/utils/autoreload.py", line 228, in wrapper
    fn(*args, **kwargs)
  File "/home/user/code/hacksoft/env/project/lib/python3.6/site-packages/django/core/management/commands/runserver.py", line 125, in inner_run
    self.check(display_num_errors=True)
  File "/home/user/code/hacksoft/env/project/lib/python3.6/site-packages/django/core/management/base.py", line 359, in check
    include_deployment_checks=include_deployment_checks,
  File "/home/user/code/hacksoft/env/project/lib/python3.6/site-packages/django/core/management/base.py", line 346, in _run_checks
    return checks.run_checks(**kwargs)
  File "/home/user/code/hacksoft/env/project/lib/python3.6/site-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/user/code/hacksoft/env/project/lib/python3.6/site-packages/wagtail/wagtailadmin/checks.py", line 65, in get_form_class_check
    if not issubclass(edit_handler.get_form_class(cls), WagtailAdminPageForm):
  File "/home/user/code/hacksoft/env/project/lib/python3.6/site-packages/wagtail/wagtailadmin/edit_handlers.py", line 318, in get_form_class
    widgets=cls.widget_overrides())
  File "/home/user/code/hacksoft/env/project/lib/python3.6/site-packages/wagtail/wagtailadmin/edit_handlers.py", line 65, in get_form_for_model
    return metaclass(class_name, (form_class,), form_class_attrs)
  File "/home/user/code/hacksoft/env/project/lib/python3.6/site-packages/wagtail/wagtailadmin/forms.py", line 295, in __new__
    new_class = super(WagtailAdminModelFormMetaclass, cls).__new__(cls, name, bases, attrs)
  File "/home/user/code/hacksoft/env/project/lib/python3.6/site-packages/modelcluster/forms.py", line 192, in __new__
    new_class = super(ClusterFormMetaclass, cls).__new__(cls, name, bases, attrs)
  File "/home/user/code/hacksoft/env/project/lib/python3.6/site-packages/django/forms/models.py", line 277, in __new__
    raise FieldError(message)
django.core.exceptions.FieldError: Unknown field(s) (slug_ru, search_description_en, slug_en, seo_title_ru, seo_title_en, search_description_ru) specified for Section
```

The project structure I have is the following:

```
class Guide(Page):
    ...

class Section(Page):
    ...
```

Sections are created as sub-pages of `Guide` and Guide is registered in `translation.py` for translation.
The `Section` model is NOT registered in `translation.py` for translation.

**Comment by dmarcelino** [comment]
Hi @kdkocev, in 0.6 `Page` model itself wasn't marked for translation and all translations happened at the subclass level by developer choice. In 0.8 `Page` model is marked for translation (at [translation.py#L10](https://github.com/infoportugal/wagtail-modeltranslation/blob/master/wagtail_modeltranslation/translation.py#L10)) hence all subclasses are too. See PR #150 for more details.

Registering `Section` for translation without declaring `fields` or declaring `fields = ()`, should clear that error.

**Comment by kdkocev** [comment]
Thank you. I will close the issue. :+1:
