### ISSUE TITLE
ModuleNotFoundError for v0.9.0

### ISSUE THREAD

**Issue by dalepotter** [infoportugal/wagtail-modeltranslation#206]
I've upgraded my wagtail project virtualenv to 0.9.0 and my builds are reporting a `ModuleNotFoundError: No module named 'django.core.urlresolvers'` error:

```
$ python manage.py check
Traceback (most recent call last):
  File "manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/dalepotter/Documents/temp/preview-website/pytest-newenv/lib/python3.6/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/Users/dalepotter/Documents/temp/preview-website/pytest-newenv/lib/python3.6/site-packages/django/core/management/__init__.py", line 347, in execute
    django.setup()
  File "/Users/dalepotter/Documents/temp/preview-website/pytest-newenv/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/dalepotter/Documents/temp/preview-website/pytest-newenv/lib/python3.6/site-packages/django/apps/registry.py", line 120, in populate
    app_config.ready()
  File "/Users/dalepotter/Documents/temp/preview-website/pytest-newenv/lib/python3.6/site-packages/wagtail_modeltranslation/apps.py", line 20, in ready
    from .patch_wagtailadmin import patch_wagtail_models
  File "/Users/dalepotter/Documents/temp/preview-website/pytest-newenv/lib/python3.6/site-packages/wagtail_modeltranslation/patch_wagtailadmin.py", line 8, in <module>
    from django.core.urlresolvers import reverse
ModuleNotFoundError: No module named 'django.core.urlresolvers'
```
This error is not present with a build running `0.8.1` (installed via pip).

Python version and installed packages are shown below:
```
$ python --version
Python 3.6.4
```

```
$ pip freeze
astroid==1.6.4
attrs==18.1.0
beautifulsoup4==4.6.0
certifi==2018.4.16
chardet==3.0.4
Django==2.0.5
django-modelcluster==4.1
django-modeltranslation==0.13b1
django-taggit==0.22.2
django-treebeard==4.3
djangorestframework==3.8.2
draftjs-exporter==2.0.0
flake8==3.5.0
html5lib==0.999999999
idna==2.6
isort==4.3.4
lazy-object-proxy==1.3.1
mccabe==0.6.1
Pillow==5.1.0
pluggy==0.6.0
psycopg2-binary==2.7.4
py==1.5.3
pycodestyle==2.3.1
pydocstyle==2.1.1
pyflakes==1.6.0
pylint==1.8.4
pylint-django==0.10.1
pylint-plugin-utils==0.2.6
pytest==3.4.1
pytest-django==3.1.2
pytest-splinter==1.8.5
pytz==2018.4
requests==2.18.4
selenium==3.12.0
six==1.11.0
snowballstemmer==1.2.1
splinter==0.8.0
Unidecode==0.4.21
urllib3==1.22
wagtail==2.0.1
wagtail-modeltranslation==0.9.0
webencodings==0.5.1
Willow==1.1
wrapt==1.10.11
You are using pip version 9.0.1, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

Project code is available here: https://github.com/IATI/preview-website/blob/6a920b7b5eed10b6e3abb0f9695002a409f444ae/iati/requirements.txt#L4

**Comment by DiogoMarques29** [comment]
Hello @dalepotter , sorry for the delayed response.
I've uploaded to pypi the files necessary to install via `pip install wagtail_modeltranslation` for python 3.
Can you check if your problem persists with this installation?

Cheers

**Comment by allthatilk** [comment]
@dalepotter The change was the addition of an import from `django.core.urlresolvers` which relies on Django <2.0 As the project you're working on relies on Django 2.0 which swapped `django.core.urlresolvers` to `django.urls` updating to wagtail-modeltranslation>0.8.1 will return your error until this fix https://github.com/infoportugal/wagtail-modeltranslation/issues/191 is merged and released.

**Comment by DiogoMarques29** [comment]
Hi @dalepotter ,
A wagtail-modeltranslation==0.10b1 is now compatible with django>=2.0
Give it a try and re-open if this issue still exists!
Cheers
