### ISSUE TITLE
issues with wagtail.Page.seo_title?

### ISSUE THREAD

**Issue by Pomax** [infoportugal/wagtail-modeltranslation#216]
I'm trying to get a db uplifted to use wagtail-modeltranslations v0.9.0, but running through makemigrations, migrate, sync and update, leads to the final update step failing with the following error:

```
c:\Users\Mike\Documents\git\collaborations\mozilla\foundation.mozilla.org>inv l10n-update
Loading .env environment variables…
System check identified some issues:

WARNINGS:
?: (mezzanine.core.W04) mezzanine.core.middleware.SitePermissionMiddleware missing from settings.MIDDLEWARE - per site permissions not applied
Using default language: en
Updating data of model '<class 'mezzanine.conf.models.Setting'>'
Updating data of model '<class 'mezzanine.pages.models.Page'>'
Updating data of model '<class 'mezzanine.pages.models.RichTextPage'>'
Updating data of model '<class 'mezzanine.pages.models.Link'>'
Updating data of model '<class 'mezzanine.forms.models.Form'>'
Updating data of model '<class 'mezzanine.forms.models.Field'>'
Updating data of model '<class 'wagtail.core.models.Page'>'
Traceback (most recent call last):
  File "C:\Users\Mike\.virtualenvs\foundation.mozilla.org-X7v0FXSr\lib\site-packages\django\db\backends\utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
psycopg2.ProgrammingError: column wagtailcore_page.seo_title_en does not exist
LINE 1: ...title_en" = "wagtailcore_page"."seo_title" WHERE ("wagtailco...
                                                             ^
HINT:  Perhaps you meant to reference the column "wagtailcore_page.seo_title".


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "network-api/manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\Mike\.virtualenvs\foundation.mozilla.org-X7v0FXSr\lib\site-packages\django\core\management\__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "C:\Users\Mike\.virtualenvs\foundation.mozilla.org-X7v0FXSr\lib\site-packages\django\core\management\__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\Mike\.virtualenvs\foundation.mozilla.org-X7v0FXSr\lib\site-packages\django\core\management\base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Users\Mike\.virtualenvs\foundation.mozilla.org-X7v0FXSr\lib\site-packages\django\core\management\base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "C:\Users\Mike\.virtualenvs\foundation.mozilla.org-X7v0FXSr\lib\site-packages\modeltranslation\management\commands\update_translation_fields.py", line 33, in handle
    **{def_lang_fieldname: F(field_name)})
  File "C:\Users\Mike\.virtualenvs\foundation.mozilla.org-X7v0FXSr\lib\site-packages\modeltranslation\manager.py", line 383, in update
    return super(MultilingualQuerySet, self).update(**kwargs)
  File "C:\Users\Mike\.virtualenvs\foundation.mozilla.org-X7v0FXSr\lib\site-packages\django\db\models\query.py", line 647, in update
    rows = query.get_compiler(self.db).execute_sql(CURSOR)
  File "C:\Users\Mike\.virtualenvs\foundation.mozilla.org-X7v0FXSr\lib\site-packages\django\db\models\sql\compiler.py", line 1204, in execute_sql
    cursor = super(SQLUpdateCompiler, self).execute_sql(result_type)
  File "C:\Users\Mike\.virtualenvs\foundation.mozilla.org-X7v0FXSr\lib\site-packages\django\db\models\sql\compiler.py", line 899, in execute_sql
    raise original_exception
  File "C:\Users\Mike\.virtualenvs\foundation.mozilla.org-X7v0FXSr\lib\site-packages\django\db\models\sql\compiler.py", line 889, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\Mike\.virtualenvs\foundation.mozilla.org-X7v0FXSr\lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "C:\Users\Mike\.virtualenvs\foundation.mozilla.org-X7v0FXSr\lib\site-packages\django\db\backends\utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Mike\.virtualenvs\foundation.mozilla.org-X7v0FXSr\lib\site-packages\django\db\utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "C:\Users\Mike\.virtualenvs\foundation.mozilla.org-X7v0FXSr\lib\site-packages\django\utils\six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Mike\.virtualenvs\foundation.mozilla.org-X7v0FXSr\lib\site-packages\django\db\backends\utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: column wagtailcore_page.seo_title_en does not exist
LINE 1: ...title_en" = "wagtailcore_page"."seo_title" WHERE ("wagtailco...
                                                             ^
HINT:  Perhaps you meant to reference the column "wagtailcore_page.seo_title".
```

**Comment by DiogoMarques29** [comment]
Hello @Pomax 
This was undocumented #217 , are you missing the app `wagtail_modeltranslation.migrate` in your project settings?

**Comment by Pomax** [comment]
Ahh, I am. My settings.py has:
```
    'wagtail_modeltranslation',
    'wagtail_modeltranslation.makemigrations'
```
but no `wagtail_modeltranslation.migrate`.
