### ISSUE TITLE
ValidationError at /admin/pages/2/delete/

### ISSUE THREAD

**Issue by Sempiternal02** [infoportugal/wagtail-modeltranslation#218]
I can not delete the default page that is created when the first migration.

Internal Server Error: /admin/pages/2/delete/
Traceback (most recent call last):
  File "/home/vladyslav/PycharmProjects/juliafineart-project/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/vladyslav/PycharmProjects/juliafineart-project/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/vladyslav/PycharmProjects/juliafineart-project/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/vladyslav/PycharmProjects/juliafineart-project/venv/lib/python3.6/site-packages/django/views/decorators/cache.py", line 43, in _cache_controlled
    response = viewfunc(request, *args, **kw)
  File "/home/vladyslav/PycharmProjects/juliafineart-project/venv/lib/python3.6/site-packages/wagtail/admin/urls/__init__.py", line 102, in wrapper
    return view_func(request, *args, **kwargs)
  File "/home/vladyslav/PycharmProjects/juliafineart-project/venv/lib/python3.6/site-packages/wagtail/admin/decorators.py", line 34, in decorated_view
    return view_func(request, *args, **kwargs)
  File "/home/vladyslav/PycharmProjects/juliafineart-project/venv/lib/python3.6/site-packages/wagtail/admin/views/pages.py", line 552, in delete
    page.delete()
  File "/home/vladyslav/PycharmProjects/juliafineart-project/venv/lib/python3.6/site-packages/wagtail/core/models.py", line 494, in delete
    return super().delete(*args, **kwargs)
  File "/home/vladyslav/PycharmProjects/juliafineart-project/venv/lib/python3.6/site-packages/treebeard/models.py", line 510, in delete
    self.__class__.objects.filter(pk=self.pk).delete()
  File "/home/vladyslav/PycharmProjects/juliafineart-project/venv/lib/python3.6/site-packages/treebeard/mp_tree.py", line 116, in delete
    parent.save()
  File "/usr/lib/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/home/vladyslav/PycharmProjects/juliafineart-project/venv/lib/python3.6/site-packages/wagtail_modeltranslation/patch_wagtailadmin.py", line 531, in __call__
    result = self.func(instance, *args, **kwargs)
  File "/usr/lib/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/home/vladyslav/PycharmProjects/juliafineart-project/venv/lib/python3.6/site-packages/wagtail/core/models.py", line 442, in save
    self.full_clean()
  File "/home/vladyslav/PycharmProjects/juliafineart-project/venv/lib/python3.6/site-packages/wagtail/core/models.py", line 432, in full_clean
    super().full_clean(*args, **kwargs)
  File "/home/vladyslav/PycharmProjects/juliafineart-project/venv/lib/python3.6/site-packages/django/db/models/base.py", line 1250, in full_clean
    raise ValidationError(errors)
django.core.exceptions.ValidationError: {'title': ['Это поле не может быть пустым.'], 'title_uk': ['Это поле не может быть пустым.'], 'slug': ['Это поле не может быть пустым.'], 'slug_uk': ['Это поле не может быть пустым.']}

**Comment by DiogoMarques29** [comment]
Hi @Sempiternal02 
I can not replicate the issue, when i first run migration in a new project page with pk=2 does not exists.
What version of wagtail and wagtail-modeltranslation are you using?
Cheers

**Comment by MerlinB** [comment]
Ran into the same issue. As @jordanmt pointed out, wagtails root pages `title` field is blank, despite not being allowed to. Deleting any direct child results in `save()` being called on the root page, failing. This is not the case when starting a new wagtail project, where the root page is titled "Root". I assume this might be an issue with wagtail not setting the title when integrating wagtail into an existing project. Giving the root page a title solves the issue.

**Comment by MerlinB** [comment]
Turns out this is easily solved by running `python manage.py update_translation_fields`. See [docs].(https://wagtail-modeltranslation.readthedocs.io/en/latest/management%20commands.html#the-update-translation-fields-command)

**Comment by mariod3w** [comment]
@MerlinB Thanks

**Comment by MiriamArbaji** [comment]
> Turns out this is easily solved by running `python manage.py update_translation_fields`. See [docs](https://wagtail-modeltranslation.readthedocs.io/en/latest/management%20commands.html#the-update-translation-fields-command).

Life Savior! it worked like charm
