### ISSUE TITLE
removing a model causes errors

### ISSUE THREAD

**Issue by Pomax** [infoportugal/wagtail-modeltranslation#226]
I'm trying to remove a previous used and now unused model from my wagtail setup, where I've removed it from my model, and removed mention of that model from the translations.py file as well, but both `manage update_translation_fields` and `manage sync_page_translation_fields` now error out, saying:

```
J:\Junctions\Users\Mike\Documents\Git\collaborations\mozilla\foundation.mozilla.org>inv manage update_translation_fields
Loading .env environment variables…
Traceback (most recent call last):
  File "C:\Users\Mike\.virtualenvs\foundation.mozilla.org-X7v0FXSr\lib\site-packages\django\db\models\options.py", line 617, in get_field
    return self.fields_map[field_name]
KeyError: 'body_en'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "network-api/manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\Mike\.virtualenvs\foundation.mozilla.org-X7v0FXSr\lib\site-packages\django\core\management\__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "C:\Users\Mike\.virtualenvs\foundation.mozilla.org-X7v0FXSr\lib\site-packages\django\core\management\__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\Mike\.virtualenvs\foundation.mozilla.org-X7v0FXSr\lib\site-packages\django\core\management\base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Users\Mike\.virtualenvs\foundation.mozilla.org-X7v0FXSr\lib\site-packages\django\core\management\base.py", line 327, in execute
    self.check()
  File "C:\Users\Mike\.virtualenvs\foundation.mozilla.org-X7v0FXSr\lib\site-packages\django\core\management\base.py", line 359, in check
    include_deployment_checks=include_deployment_checks,
  File "C:\Users\Mike\.virtualenvs\foundation.mozilla.org-X7v0FXSr\lib\site-packages\django\core\management\base.py", line 346, in _run_checks
    return checks.run_checks(**kwargs)
  File "C:\Users\Mike\.virtualenvs\foundation.mozilla.org-X7v0FXSr\lib\site-packages\django\core\checks\registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "C:\Users\Mike\.virtualenvs\foundation.mozilla.org-X7v0FXSr\lib\site-packages\wagtail\admin\checks.py", line 62, in get_form_class_check
    edit_handler = cls.get_edit_handler()
  File "C:\Users\Mike\.virtualenvs\foundation.mozilla.org-X7v0FXSr\lib\site-packages\wagtail\utils\decorators.py", line 53, in __call__
    return self.value
  File "C:\Users\Mike\.virtualenvs\foundation.mozilla.org-X7v0FXSr\lib\site-packages\django\utils\functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\Mike\.virtualenvs\foundation.mozilla.org-X7v0FXSr\lib\site-packages\wagtail\utils\decorators.py", line 49, in value
    return self.fn(self.cls)
  File "C:\Users\Mike\.virtualenvs\foundation.mozilla.org-X7v0FXSr\lib\site-packages\wagtail\admin\edit_handlers.py", line 804, in get_edit_handler
    return edit_handler.bind_to_model(cls)
  File "C:\Users\Mike\.virtualenvs\foundation.mozilla.org-X7v0FXSr\lib\site-packages\wagtail\admin\edit_handlers.py", line 131, in bind_to_model
    new.on_model_bound()
  File "C:\Users\Mike\.virtualenvs\foundation.mozilla.org-X7v0FXSr\lib\site-packages\wagtail\admin\edit_handlers.py", line 280, in on_model_bound
    for child in self.children]
  File "C:\Users\Mike\.virtualenvs\foundation.mozilla.org-X7v0FXSr\lib\site-packages\wagtail\admin\edit_handlers.py", line 280, in <listcomp>
    for child in self.children]
  File "C:\Users\Mike\.virtualenvs\foundation.mozilla.org-X7v0FXSr\lib\site-packages\wagtail\admin\edit_handlers.py", line 131, in bind_to_model
    new.on_model_bound()
  File "C:\Users\Mike\.virtualenvs\foundation.mozilla.org-X7v0FXSr\lib\site-packages\wagtail\admin\edit_handlers.py", line 280, in on_model_bound
    for child in self.children]
  File "C:\Users\Mike\.virtualenvs\foundation.mozilla.org-X7v0FXSr\lib\site-packages\wagtail\admin\edit_handlers.py", line 280, in <listcomp>
    for child in self.children]
  File "C:\Users\Mike\.virtualenvs\foundation.mozilla.org-X7v0FXSr\lib\site-packages\wagtail\admin\edit_handlers.py", line 131, in bind_to_model
    new.on_model_bound()
  File "C:\Users\Mike\.virtualenvs\foundation.mozilla.org-X7v0FXSr\lib\site-packages\wagtail\admin\edit_handlers.py", line 835, in on_model_bound
    self.block_def = self.db_field.stream_block
  File "C:\Users\Mike\.virtualenvs\foundation.mozilla.org-X7v0FXSr\lib\site-packages\django\utils\functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\Mike\.virtualenvs\foundation.mozilla.org-X7v0FXSr\lib\site-packages\wagtail\admin\edit_handlers.py", line 515, in db_field
    return model._meta.get_field(self.field_name)
  File "C:\Users\Mike\.virtualenvs\foundation.mozilla.org-X7v0FXSr\lib\site-packages\django\db\models\options.py", line 619, in get_field
    raise FieldDoesNotExist("%s has no field named '%s'" % (self.object_name, field_name))
django.core.exceptions.FieldDoesNotExist: ParticipatePage has no field named 'body_en'
```

Which... should be irrelevant if I'm trying to remove it?

I have both wagtail's migrate and makemigrations in my installed apps:
```
INSTALLED_APPS = list(filter(None, [
    ...
    'wagtail_modeltranslation.makemigrations',
    'wagtail_modeltranslation.migrate',
    ...
]))
```

**Comment by DiogoMarques29** [comment]
Hi @Pomax 
Have you run `makemigrations` and `migrate` commands?
I tried to replicate your problem but all seams fine.

Cheers

**Comment by Pomax** [comment]
`makemigrations` works, but migrating then crashes (steps: I remove my class from models.py and translations.py, make sure no other class references it as a parent or child page, then run makemigations, and then migrate):
```
>pipenv run python network-api\manage.py migrate
Loading .env environment variables…
Operations to perform:
  Apply all migrations: admin, auth, buyersguide, campaign, contenttypes, experiments, highlights, milestones, news, people, redirects, sessions, sites, social_django, taggit, wagtailadmin, wagtailcore, wagtaildocs, wagtailembeds, wagtailforms, wagtailimages, wagtailinventory, wagtailmetadata, wagtailpages, wagtailredirects, wagtailsearch, wagtailusers
Running migrations:
  Applying wagtailpages.0044_auto_20190201_1035...Traceback (most recent call last):
  File "C:\Users\Mike\.virtualenvs\foundation.mozilla.org-4aDC7Y6j\lib\site-packages\django\db\backends\utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Mike\.virtualenvs\foundation.mozilla.org-4aDC7Y6j\lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: near ")": syntax error

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "network-api\manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\Mike\.virtualenvs\foundation.mozilla.org-4aDC7Y6j\lib\site-packages\django\core\management\__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "C:\Users\Mike\.virtualenvs\foundation.mozilla.org-4aDC7Y6j\lib\site-packages\django\core\management\__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\Mike\.virtualenvs\foundation.mozilla.org-4aDC7Y6j\lib\site-packages\django\core\management\base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Users\Mike\.virtualenvs\foundation.mozilla.org-4aDC7Y6j\lib\site-packages\django\core\management\base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "C:\Users\Mike\.virtualenvs\foundation.mozilla.org-4aDC7Y6j\lib\site-packages\wagtail_modeltranslation\management\commands\migrate_translation.py", line 25, in handle
    super(Command, self).handle(*args, **options)
  File "C:\Users\Mike\.virtualenvs\foundation.mozilla.org-4aDC7Y6j\lib\site-packages\django\core\management\commands\migrate.py", line 204, in handle
    fake_initial=fake_initial,
  File "C:\Users\Mike\.virtualenvs\foundation.mozilla.org-4aDC7Y6j\lib\site-packages\django\db\migrations\executor.py", line 115, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "C:\Users\Mike\.virtualenvs\foundation.mozilla.org-4aDC7Y6j\lib\site-packages\django\db\migrations\executor.py", line 145, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "C:\Users\Mike\.virtualenvs\foundation.mozilla.org-4aDC7Y6j\lib\site-packages\django\db\migrations\executor.py", line 244, in apply_migration
    state = migration.apply(state, schema_editor)
  File "C:\Users\Mike\.virtualenvs\foundation.mozilla.org-4aDC7Y6j\lib\site-packages\django\db\migrations\migration.py", line 129, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "C:\Users\Mike\.virtualenvs\foundation.mozilla.org-4aDC7Y6j\lib\site-packages\django\db\migrations\operations\fields.py", line 156, in database_forwards
    schema_editor.remove_field(from_model, from_model._meta.get_field(self.name))
  File "C:\Users\Mike\.virtualenvs\foundation.mozilla.org-4aDC7Y6j\lib\site-packages\django\db\backends\sqlite3\schema.py", line 256, in remove_field
    self._remake_table(model, delete_field=field)
  File "C:\Users\Mike\.virtualenvs\foundation.mozilla.org-4aDC7Y6j\lib\site-packages\django\db\backends\sqlite3\schema.py", line 206, in _remake_table
    self.quote_name(model._meta.db_table),
  File "C:\Users\Mike\.virtualenvs\foundation.mozilla.org-4aDC7Y6j\lib\site-packages\django\db\backends\base\schema.py", line 136, in execute
    cursor.execute(sql, params)
  File "C:\Users\Mike\.virtualenvs\foundation.mozilla.org-4aDC7Y6j\lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "C:\Users\Mike\.virtualenvs\foundation.mozilla.org-4aDC7Y6j\lib\site-packages\django\db\backends\utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Mike\.virtualenvs\foundation.mozilla.org-4aDC7Y6j\lib\site-packages\django\db\utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "C:\Users\Mike\.virtualenvs\foundation.mozilla.org-4aDC7Y6j\lib\site-packages\django\utils\six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Mike\.virtualenvs\foundation.mozilla.org-4aDC7Y6j\lib\site-packages\django\db\backends\utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Mike\.virtualenvs\foundation.mozilla.org-4aDC7Y6j\lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: near ")": syntax error
```

The migration file itself:
```
# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-01 18:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailinventory', '0001_initial'),
        ('wagtailcore', '0040_page_draft_title'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailredirects', '0005_capitalizeverbose'),
        ('wagtailpages', '0043_auto_20190108_2000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participatepage',
            name='primarypage_ptr',
        ),
        migrations.DeleteModel(
            name='ParticipatePage',
        ),
    ]
```

**Comment by DiogoMarques29** [comment]
We don't have tests for SQLite, it shouldn't be a problem, but at the moment it's my best bet.
Try and activate query logging so we can take a look at it

**Comment by Pomax** [comment]
I'm now testing this with postgres rather than sqlite3, and I'm still seeing this. If you clone/checkout https://github.com/mozilla/foundation.mozilla.org/tree/rmv-ppl-class-test-branch-for-wmt and run `inv setup` (prerequisites: python 3 at 3.6 or above, `pipenv`, and `invoke`) you'll see it crash out citing:

```
Warning: Your Pipfile requires python_version 3.6, but you are using 3.7.2
  $ pipenv --rm and rebuilding the virtual environment may resolve the issue.
  $ pipenv check will surely fail.
Loading .env environment variables…
Traceback (most recent call last):
  File "C:\blah\.virtualenvs\foundation.mozilla.org-...\lib\site-packages\django\db\models\options.py", line 617, in get_field
    return self.fields_map[field_name]
KeyError: 'body_en'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "network-api/manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "C:\blah\.virtualenvs\foundation.mozilla.org-...\lib\site-packages\django\core\management\__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "C:\blah\.virtualenvs\foundation.mozilla.org-...\lib\site-packages\django\core\management\__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\blah\.virtualenvs\foundation.mozilla.org-...\lib\site-packages\django\core\management\base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\blah\.virtualenvs\foundation.mozilla.org-...\lib\site-packages\django\core\management\base.py", line 327, in execute
    self.check()
  File "C:\blah\.virtualenvs\foundation.mozilla.org-...\lib\site-packages\django\core\management\base.py", line 359, in check
    include_deployment_checks=include_deployment_checks,
  File "C:\blah\.virtualenvs\foundation.mozilla.org-...\lib\site-packages\django\core\management\base.py", line 346, in _run_checks
    return checks.run_checks(**kwargs)
  File "C:\blah\.virtualenvs\foundation.mozilla.org-...\lib\site-packages\django\core\checks\registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "C:\blah\.virtualenvs\foundation.mozilla.org-...\lib\site-packages\wagtail\admin\checks.py", line 62, in get_form_class_check
    edit_handler = cls.get_edit_handler()
  File "C:\blah\.virtualenvs\foundation.mozilla.org-...\lib\site-packages\wagtail\utils\decorators.py", line 53, in __call__
    return self.value
  File "C:\blah\.virtualenvs\foundation.mozilla.org-...\lib\site-packages\django\utils\functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\blah\.virtualenvs\foundation.mozilla.org-...\lib\site-packages\wagtail\utils\decorators.py", line 49, in value
    return self.fn(self.cls)
  File "C:\blah\.virtualenvs\foundation.mozilla.org-...\lib\site-packages\wagtail\admin\edit_handlers.py", line 804, in get_edit_handler
    return edit_handler.bind_to_model(cls)
  File "C:\blah\.virtualenvs\foundation.mozilla.org-...\lib\site-packages\wagtail\admin\edit_handlers.py", line 131, in bind_to_model
    new.on_model_bound()
  File "C:\blah\.virtualenvs\foundation.mozilla.org-...\lib\site-packages\wagtail\admin\edit_handlers.py", line 280, in on_model_bound
    for child in self.children]
  File "C:\blah\.virtualenvs\foundation.mozilla.org-...\lib\site-packages\wagtail\admin\edit_handlers.py", line 280, in <listcomp>
    for child in self.children]
  File "C:\blah\.virtualenvs\foundation.mozilla.org-...\lib\site-packages\wagtail\admin\edit_handlers.py", line 131, in bind_to_model
    new.on_model_bound()
  File "C:\blah\.virtualenvs\foundation.mozilla.org-...\lib\site-packages\wagtail\admin\edit_handlers.py", line 280, in on_model_bound
    for child in self.children]
  File "C:\blah\.virtualenvs\foundation.mozilla.org-...\lib\site-packages\wagtail\admin\edit_handlers.py", line 280, in <listcomp>
    for child in self.children]
  File "C:\blah\.virtualenvs\foundation.mozilla.org-...\lib\site-packages\wagtail\admin\edit_handlers.py", line 131, in bind_to_model
    new.on_model_bound()
  File "C:\blah\.virtualenvs\foundation.mozilla.org-...\lib\site-packages\wagtail\admin\edit_handlers.py", line 835, in on_model_bound
    self.block_def = self.db_field.stream_block
  File "C:\blah\.virtualenvs\foundation.mozilla.org-...\lib\site-packages\django\utils\functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\blah\.virtualenvs\foundation.mozilla.org-...\lib\site-packages\wagtail\admin\edit_handlers.py", line 515, in db_field
    return model._meta.get_field(self.field_name)
  File "C:\blah\.virtualenvs\foundation.mozilla.org-...\lib\site-packages\django\db\models\options.py", line 619, in get_field
    raise FieldDoesNotExist("%s has no field named '%s'" % (self.object_name, field_name))
django.core.exceptions.FieldDoesNotExist: PeoplePage has no field named 'body_en'
```

Give or take a difference in path names of course. So this issue should probably be reopened: we can't really remove obsolete models it would appear, irrespective of the database choice.

**Comment by vbroskas** [comment]
@Pomax did you end up finding a solution for this? I'm trying to remove an app I no longer need (which I had previously been doing translations for) However after removing it, and removing it from my `INSTALLED_APPS` and trying to `makemigrations/migrate` I get the error:

```
django.core.exceptions.FieldError: Unknown field(s) (seo_title_ko, slug_vi, seo_title_ja, seo_title_zh_hant, seo_title_fa, slug_zh_hans, search_description_fa, slug_ko, slug_hi, seo_title_hi, search_description_vi, search_description_ko, search_description_en, slug_en, search_description_zh_hant, seo_title_zh_hans, slug_zh_hant, slug_ja, slug_fa, search_description_hi, seo_title_en, seo_title_vi, search_description_zh_hans, search_description_ja) specified for GroupPage
```
Where GroupPage was a page was an extended page from the app

**Comment by Pomax** [comment]
I'm afraid not.
