### ISSUE TITLE
Streamfield is not supported by modeltranslation error

### ISSUE THREAD

**Issue by cadecairos** [infoportugal/wagtail-modeltranslation#234]
I'm trying to upgrade wagtail-modeltranslation from 0.9.0 to 0.10, and I'm hitting this error for an unknown reason:

```
django.core.exceptions.ImproperlyConfigured: StreamField is not supported by modeltranslation.
```

I've checked out the [other issue](https://github.com/infoportugal/wagtail-modeltranslation/issues/139) that mentioned this error but haven't been able to fix the issue using the method specified there.

#### translation.py

```
from .models import ModularPage

from modeltranslation.translator import TranslationOptions
from modeltranslation.decorators import register


@register(ModularPage)
class ModularPageTR(TranslationOptions):
    fields = (
        'header',
        'body',
    )
```

#### models.py

```
class ModularPage(FoundationMetadataPageMixin, Page):
    """
    The base class offers universal component picking
    """

    header = models.CharField(
        max_length=250,
        blank=True
    )

    narrowed_page_content = models.BooleanField(
        default=False,
        help_text='For text-heavy pages, turn this on to reduce the overall width of the content on the page.'
    )

    zen_nav = models.BooleanField(
        default=True,
        help_text='For secondary nav pages, use this to collapse the primary nav under a toggle hamburger.'
    )

    body = StreamField(base_fields)

    settings_panels = Page.settings_panels + [
        MultiFieldPanel([
            FieldPanel('narrowed_page_content'),
        ]),
        MultiFieldPanel([
            FieldPanel('zen_nav'),
        ])
    ]

    content_panels = Page.content_panels + [
        FieldPanel('header'),
        StreamFieldPanel('body'),
    ]

    @property
    def meta_title(self):
        return self.title

    show_in_menus_default = True

```

#### settings.py

```
INSTALLED_APPS = (
    ...
    'wagtail_modeltranslation',
    'wagtail_modeltranslation.makemigrations',
    'wagtail_modeltranslation.migrate',
    ...
)

LANGUAGE_CODE = 'en'
LANGUAGES = (
    ('en', _('English')),
    ('de', _('German')),
    ('pt', _('Portuguese')),
    ('es', _('Spanish')),
    ('fr', _('French')),
    ('pl', _('Polish')),
)

USE_I18N = True
USE_L10N = True
```

#### Versions

- Wagtail 2.4
- django 2.1.7
- wagtail-modeltranslation 0.10

There's more to these files that I've shared here, the full sources can be [found in our repo](https://github.com/mozilla/foundation.mozilla.org)

- [models.py](https://github.com/mozilla/foundation.mozilla.org/blob/5c2811e73773c863a5760a9a2e52e42d839a6263/network-api/networkapi/wagtailpages/models.py)
- [translation.py](https://github.com/mozilla/foundation.mozilla.org/blob/5c2811e73773c863a5760a9a2e52e42d839a6263/network-api/networkapi/wagtailpages/translation.py)
- [settings.py](https://github.com/mozilla/foundation.mozilla.org/blob/5c2811e73773c863a5760a9a2e52e42d839a6263/network-api/networkapi/settings.py)

Glad to provide any additional iformation as required.

**Comment by Pomax** [comment]
I've had a look to see what `django-modeltranslation` actually used, and based on that it looks like https://github.com/infoportugal/wagtail-modeltranslation/blob/master/wagtail_modeltranslation/apps.py#L12-L15, which currently reads:
```
        from django.conf import settings
        # Add Wagtail defined fields as modeltranslation custom fields
        setattr(settings, 'MODELTRANSLATION_CUSTOM_FIELDS', getattr(settings, 'MODELTRANSLATION_CUSTOM_FIELDS', ()) + (
            'StreamField', 'RichTextField'))
```
Should instead read:
```
        from modeltranslation import settings
        # Add Wagtail defined fields as modeltranslation custom fields
        setattr(settings, 'CUSTOM_FIELDS', getattr(settings, 'CUSTOM_FIELDS', ()) + (
            'StreamField', 'RichTextField'))
```
With that change, I am able to run `manage migrate` to completion without any prompts or problems.

**Comment by Pomax** [comment]
After applying this fix, I can see things working fine until running the `inv manage load_fake_data` command. When it hits the "Generating Opportunity Pages under namespace" step, an error occurs with the following trace log:
```bash
Generating Opportunity Pages under namespace
Traceback (most recent call last):
  File "network-api/manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\Mike\.virtualenvs\foundation.mozilla.org-4aDC7Y6j\lib\site-packages\django\core\management\__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "C:\Users\Mike\.virtualenvs\foundation.mozilla.org-4aDC7Y6j\lib\site-packages\django\core\management\__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\Mike\.virtualenvs\foundation.mozilla.org-4aDC7Y6j\lib\site-packages\django\core\management\base.py", line 316, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Users\Mike\.virtualenvs\foundation.mozilla.org-4aDC7Y6j\lib\site-packages\django\core\management\base.py", line 353, in execute
    output = self.handle(*args, **options)
  File "C:\Users\Mike\Documents\Git\collaborations\mozilla\foundation.mozilla.org\network-api\networkapi\management\commands\load_fake_data.py", line 298, in handle
    [OpportunityPageFactory.create(parent=opportunity_namespace) for i in range(5)]
  File "C:\Users\Mike\Documents\Git\collaborations\mozilla\foundation.mozilla.org\network-api\networkapi\management\commands\load_fake_data.py", line 298, in <listcomp>
    [OpportunityPageFactory.create(parent=opportunity_namespace) for i in range(5)]
  File "C:\Users\Mike\.virtualenvs\foundation.mozilla.org-4aDC7Y6j\lib\site-packages\factory\base.py", line 563, in create
    return cls._generate(enums.CREATE_STRATEGY, kwargs)
  File "C:\Users\Mike\.virtualenvs\foundation.mozilla.org-4aDC7Y6j\lib\site-packages\factory\base.py", line 500, in _generate
    return step.build()
  File "C:\Users\Mike\.virtualenvs\foundation.mozilla.org-4aDC7Y6j\lib\site-packages\factory\builder.py", line 272, in build
    step.resolve(pre)
  File "C:\Users\Mike\.virtualenvs\foundation.mozilla.org-4aDC7Y6j\lib\site-packages\factory\builder.py", line 221, in resolve
    self.attributes[field_name] = getattr(self.stub, field_name)
  File "C:\Users\Mike\.virtualenvs\foundation.mozilla.org-4aDC7Y6j\lib\site-packages\factory\builder.py", line 375, in __getattr__
    extra=context,
  File "C:\Users\Mike\.virtualenvs\foundation.mozilla.org-4aDC7Y6j\lib\site-packages\factory\declarations.py", line 502, in evaluate
    extra=extra,
  File "C:\Users\Mike\.virtualenvs\foundation.mozilla.org-4aDC7Y6j\lib\site-packages\factory\declarations.py", line 324, in evaluate
    return self.generate(step, defaults)
  File "C:\Users\Mike\.virtualenvs\foundation.mozilla.org-4aDC7Y6j\lib\site-packages\factory\declarations.py", line 414, in generate
    return step.recurse(subfactory, params, force_sequence=force_sequence)
  File "C:\Users\Mike\.virtualenvs\foundation.mozilla.org-4aDC7Y6j\lib\site-packages\factory\builder.py", line 233, in recurse
    return builder.build(parent_step=self, force_sequence=force_sequence)
  File "C:\Users\Mike\.virtualenvs\foundation.mozilla.org-4aDC7Y6j\lib\site-packages\factory\builder.py", line 279, in build
    kwargs=kwargs,
  File "C:\Users\Mike\.virtualenvs\foundation.mozilla.org-4aDC7Y6j\lib\site-packages\factory\base.py", line 314, in instantiate
    return self.factory._create(model, *args, **kwargs)
  File "C:\Users\Mike\.virtualenvs\foundation.mozilla.org-4aDC7Y6j\lib\site-packages\factory\django.py", line 165, in _create
    return manager.create(*args, **kwargs)
  File "C:\Users\Mike\.virtualenvs\foundation.mozilla.org-4aDC7Y6j\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\Mike\.virtualenvs\foundation.mozilla.org-4aDC7Y6j\lib\site-packages\django\db\models\query.py", line 411, in create
    obj = self.model(**kwargs)
  File "C:\Users\Mike\.virtualenvs\foundation.mozilla.org-4aDC7Y6j\lib\site-packages\modeltranslation\translator.py", line 236, in new_init
    old_init(self, *args, **kwargs)
  File "C:\Users\Mike\.virtualenvs\foundation.mozilla.org-4aDC7Y6j\lib\site-packages\django\db\models\base.py", line 485, in __init__
    raise TypeError("'%s' is an invalid keyword argument for this function" % kwarg)
TypeError: 'name_en' is an invalid keyword argument for this function
```
And I'm not entirely sure why that specific class would cause problems.

The factory code:
```python
class OpportunityPageFactory(CMSPageFactory):
    class Meta:
        model = networkapi.wagtailpages.models.OpportunityPage

    class Params:
        no_cta = Trait(cta=None)

    cta = SubFactory(SignupFactory)
```
with superclass
```
class CMSPageFactory(PageFactory):
    class Meta:
        abstract = True
        exclude = (
            'title_text',
            'header_text',
        )

    header = LazyAttribute(lambda o: o.header_text.rstrip('.'))
    title = LazyAttribute(lambda o: o.title_text.rstrip('.'))
    narrowed_page_content = Faker('boolean', chance_of_getting_true=50)
    body = Faker('streamfield', fields=streamfield_fields)

    # Lazy Values
    title_text = sentence_faker
    header_text = header_faker
```
where `PageFactory` comes from [wagtail-factories](https://github.com/mvantellingen/wagtail-factories) v1.1.0

The translation.py content for this class is:
```
from .models import (
    ModularPage,
    MiniSiteNameSpace,
    ....
    OpportunityPage,
)

from modeltranslation.translator import TranslationOptions
from modeltranslation.decorators import register
...
@register(ModularPage)
class ModularPageTR(TranslationOptions):
    fields = (
        'header',
        'body',
    )
...
@register(MiniSiteNameSpace)
class MiniSiteNameSpaceTR(TranslationOptions):
    fields = ()
...
@register(OpportunityPage)
class OpportunityPageTR(TranslationOptions):
    fields = (
    )
```
And implicitly inherits from ModularPage, given its model hierarchy:
```
class OpportunityPage(MiniSiteNameSpace):
    """
    these pages come with sign-up-for-xyz CTAs
    """
    cta = models.ForeignKey(
        'Signup',
        related_name='page',
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        help_text='Choose existing or create new petition form'
    )

    content_panels = Page.content_panels + [
        FieldPanel('header'),
        SnippetChooserPanel('cta'),
        StreamFieldPanel('body'),
    ]

    subpage_types = [
        'OpportunityPage',
        'RedirectingPage',
    ]
```
with MiniSiteNameSpace being:
```
class MiniSiteNameSpace(ModularPage):
    subpage_types = [
        'BanneredCampaignPage',
        'CampaignPage',
        'OpportunityPage',
    ]
```
and ModularPage being:
```
class ModularPage(FoundationMetadataPageMixin, Page):
    """
    The base class offers universal component picking
    """

    header = models.CharField(
        max_length=250,
        blank=True
    )

    narrowed_page_content = models.BooleanField(
        default=False,
        help_text='For text-heavy pages, turn this on to reduce the overall width of the content on the page.'
    )

    zen_nav = models.BooleanField(
        default=True,
        help_text='For secondary nav pages, use this to collapse the primary nav under a toggle hamburger.'
    )

    body = StreamField(base_fields)

    settings_panels = Page.settings_panels + [
        MultiFieldPanel([
            FieldPanel('narrowed_page_content'),
        ]),
        MultiFieldPanel([
            FieldPanel('zen_nav'),
        ])
    ]

    content_panels = Page.content_panels + [
        FieldPanel('header'),
        StreamFieldPanel('body'),
    ]

    # Legacy field for now, necessary to make sure that the
    # actualy <title> element has the correct value in it.
    # This uses page.meta_title in the base.html
    # master template, which is still based on Mezzanine
    # page models, rather than Wagtail pages models.
    @property
    def meta_title(self):
        return self.title

    show_in_menus_default = True
```
With that Page class being the `wagtail.core.models.Page` class.
