### ISSUE TITLE
sync_translation_fields TypeError with Django 2.1.7

### ISSUE THREAD

**Issue by cadecairos** [infoportugal/wagtail-modeltranslation#241]
I'm attempting to use Django 2.1.7 with wagtail 2.4, wagtail-modeltranslation 0.10.1, and postgresql 9.6.12 and am running into the following error:

`TypeError: sequence index must be integer, not 'slice'`

Here's a full stack trace:

```
/home/travis/virtualenv/python3.6.8/lib/python3.6/site-packages/environ/environ.py:630: UserWarning: /home/travis/build/mozilla/foundation.mozilla.org/network-api/networkapi/.env doesn't exist - if you're not configuring your environment separately, create one.
  "environment separately, create one." % env_file)
Traceback (most recent call last):
  File "network-api/manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/home/travis/virtualenv/python3.6.8/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/travis/virtualenv/python3.6.8/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/travis/virtualenv/python3.6.8/lib/python3.6/site-packages/django/core/management/commands/test.py", line 26, in run_from_argv
    super().run_from_argv(argv)
  File "/home/travis/virtualenv/python3.6.8/lib/python3.6/site-packages/django/core/management/base.py", line 316, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/travis/virtualenv/python3.6.8/lib/python3.6/site-packages/django/core/management/base.py", line 353, in execute
    output = self.handle(*args, **options)
  File "/home/travis/virtualenv/python3.6.8/lib/python3.6/site-packages/django/core/management/commands/test.py", line 56, in handle
    failures = test_runner.run_tests(test_labels)
  File "/home/travis/virtualenv/python3.6.8/lib/python3.6/site-packages/django/test/runner.py", line 604, in run_tests
    old_config = self.setup_databases()
  File "/home/travis/virtualenv/python3.6.8/lib/python3.6/site-packages/django/test/runner.py", line 551, in setup_databases
    self.parallel, **kwargs
  File "/home/travis/virtualenv/python3.6.8/lib/python3.6/site-packages/django/test/utils.py", line 174, in setup_databases
    serialize=connection.settings_dict.get('TEST', {}).get('SERIALIZE', True),
  File "/home/travis/virtualenv/python3.6.8/lib/python3.6/site-packages/django/db/backends/base/creation.py", line 68, in create_test_db
    run_syncdb=True,
  File "/home/travis/virtualenv/python3.6.8/lib/python3.6/site-packages/django/core/management/__init__.py", line 148, in call_command
    return command.execute(*args, **defaults)
  File "/home/travis/virtualenv/python3.6.8/lib/python3.6/site-packages/django/core/management/base.py", line 353, in execute
    output = self.handle(*args, **options)
  File "/home/travis/virtualenv/python3.6.8/lib/python3.6/site-packages/wagtail_modeltranslation/management/commands/migrate_translation.py", line 33, in handle
    sync_page_command.handle(*args, **options)
  File "/home/travis/virtualenv/python3.6.8/lib/python3.6/site-packages/wagtail_modeltranslation/management/commands/sync_page_translation_fields.py", line 26, in handle
    super(Command, self).handle(*args, **options)
  File "/home/travis/virtualenv/python3.6.8/lib/python3.6/site-packages/modeltranslation/management/commands/sync_translation_fields.py", line 83, in handle
    missing_langs = list(self.get_missing_languages(column_name, db_table))
  File "/home/travis/virtualenv/python3.6.8/lib/python3.6/site-packages/modeltranslation/management/commands/sync_translation_fields.py", line 112, in get_missing_languages
    db_table_fields = self.get_table_fields(db_table)
  File "/home/travis/virtualenv/python3.6.8/lib/python3.6/site-packages/modeltranslation/management/commands/sync_translation_fields.py", line 105, in get_table_fields
    db_table_desc = self.introspection.get_table_description(self.cursor, db_table)
  File "/home/travis/virtualenv/python3.6.8/lib/python3.6/site-packages/django/db/backends/postgresql/introspection.py", line 69, in get_table_description
    for line in cursor.description
  File "/home/travis/virtualenv/python3.6.8/lib/python3.6/site-packages/django/db/backends/postgresql/introspection.py", line 69, in <listcomp>
    for line in cursor.description
TypeError: sequence index must be integer, not 'slice'
```

I dug into `django/db/backends/postgresql/introspection.py` and found that the method that the management command `sync_translation_fields` calls (`get_table_description`) fails in Django 2.1 possibly due to [this change in introspection.py about a year ago](https://github.com/django/django/commit/f3a98224e6dd5f8846008512f281e452dc3b1909#diff-7f14932a08ce1dbba14da7433e47f9fcL78)

This might be an issue specifically with django-modeltranslation, if so, I can re-file it there.

**Comment by DiogoMarques29** [comment]
Hi @cadecairos 
`sync_translation_fields` is a management command from django-modeltranslation package. 
https://github.com/deschler/django-modeltranslation/blob/master/modeltranslation/management/commands/sync_translation_fields.py#L105

**Comment by cadecairos** [comment]
Thanks for the reply, I've filed this here: https://github.com/deschler/django-modeltranslation/issues/504

**Comment by Pomax** [comment]
@DiogoMarques29 maybe you've seen this before, and know how to recover from it - https://github.com/Pomax/wagtest shows off the error we're running into, even with Wagtail 2.1.3, Django 2.1.3, and wagtail-modeltranslation 0.10.1 (I've let the django-modeltranslation folks know about that repo, too, but I'm not super confident they care enough to want to look at it... =x)

**Comment by Pomax** [comment]
turns out they did! psycopg2 2.8 is literally incompatible with Django at the moment due to a breaking change on a minor version update... but the next Django version should be 2.8 compatible.

**Comment by DiogoMarques29** [comment]
@Pomax 
Thanks for the help, let's wait for the next Django version!
