### ISSUE TITLE
Publish page fails

### ISSUE THREAD

**Issue by dim1triy** [infoportugal/wagtail-modeltranslation#242]
Edit home page, draft save all ok. Then publish page this error

django                   2.2
wagtail                  2.5
wagtail-modeltranslation 0.10.1 

`
Environment:

Request Method: POST
Request URL: http://127.0.0.1:8000/admin/pages/3/edit/

Django Version: 2.2
Python Version: 3.7.3
Installed Applications:
['wagtail.contrib.forms',
 'wagtail.contrib.redirects',
 'wagtail.embeds',
 'wagtail.sites',
 'wagtail.users',
 'wagtail.snippets',
 'wagtail.documents',
 'wagtail.images',
 'wagtail.search',
 'wagtail.admin',
 'wagtail.core',
 'modelcluster',
 'taggit',
 'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'wagtail_modeltranslation',
 'wagtail_modeltranslation.makemigrations',
 'wagtail_modeltranslation.migrate',
 'home',
 'search']
Installed Middleware:
['django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'django.middleware.security.SecurityMiddleware',
 'wagtail.core.middleware.SiteMiddleware',
 'wagtail.contrib.redirects.middleware.RedirectMiddleware']

Traceback:

File ".../python3.7/site-packages/django/core/handlers/exception.py" in inner
  34.             response = get_response(request)

File ".../python3.7/site-packages/django/core/handlers/base.py" in _get_response
  115.                 response = self.process_exception_by_middleware(e, request)

File ".../python3.7/site-packages/django/core/handlers/base.py" in _get_response
  113.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File ".../python3.7/site-packages/django/views/decorators/cache.py" in _wrapped_view_func
  44.         response = view_func(request, *args, **kwargs)

File ".../python3.7/site-packages/wagtail/admin/urls/__init__.py" in wrapper
  102.             return view_func(request, *args, **kwargs)

File ".../python3.7/site-packages/wagtail/admin/decorators.py" in decorated_view
  34.             return view_func(request, *args, **kwargs)

File ".../python3.7/site-packages/wagtail/admin/views/pages.py" in edit
  368.                 revision.publish()

File ".../python3.7/site-packages/wagtail/core/models.py" in publish
  1538.         page.save()

File "/home/dimon/.pyenv/versions/3.7.3/lib/python3.7/contextlib.py" in inner
  74.                 return func(*args, **kwds)

File ".../python3.7/site-packages/wagtail_modeltranslation/patch_wagtailadmin.py" in __call__
  539.             _update_translation_descendant_url_paths(old_record, instance)

File ".../python3.7/site-packages/wagtail_modeltranslation/patch_wagtailadmin.py" in _update_translation_descendant_url_paths
  470.         _localized_update_descendant_url_paths(page, old_url_path, new_url_path, language)

File ".../python3.7/site-packages/wagtail_modeltranslation/patch_wagtailadmin.py" in _localized_update_descendant_url_paths
  402.                 Substr(localized_url_path, len(old_url_path) + 1))}))

Exception Type: TypeError at /admin/pages/3/edit/
Exception Value: object of type 'NoneType' has no len()
`

**Comment by tombreit** [comment]
Same here. Publish or delete page action fails with ``TypeError: object of type 'NoneType' has no len()``

In my case this happens when trying to delete the database and migrating from scratch, than try to delete the automatically created "Welcome to wagtail"  ``Page`` instance: 

```python 
Internal Server Error: /admin/pages/2/edit/
Traceback (most recent call last):
  File ".venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File ".venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File ".venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File ".venv/lib/python3.7/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File ".venv/lib/python3.7/site-packages/wagtail/admin/urls/__init__.py", line 102, in wrapper
    return view_func(request, *args, **kwargs)
  File ".venv/lib/python3.7/site-packages/wagtail/admin/decorators.py", line 34, in decorated_view
    return view_func(request, *args, **kwargs)
  File ".venv/lib/python3.7/site-packages/wagtail/admin/views/pages.py", line 366, in edit
    revision.publish()
  File ".venv/lib/python3.7/site-packages/wagtail/core/models.py", line 1516, in publish
    page.save()
  File "/usr/lib/python3.7/contextlib.py", line 74, in inner
    return func(*args, **kwds)
  File ".venv/lib/python3.7/site-packages/wagtail_modeltranslation/patch_wagtailadmin.py", line 539, in __call__
    _update_translation_descendant_url_paths(old_record, instance)
  File ".venv/lib/python3.7/site-packages/wagtail_modeltranslation/patch_wagtailadmin.py", line 470, in _update_translation_descendant_url_paths
    _localized_update_descendant_url_paths(page, old_url_path, new_url_path, language)
  File ".venv/lib/python3.7/site-packages/wagtail_modeltranslation/patch_wagtailadmin.py", line 402, in _localized_update_descendant_url_paths
    Substr(localized_url_path, len(old_url_path) + 1))}))
TypeError: object of type 'NoneType' has no len()
```

**Comment by DiogoMarques29** [comment]
@dim1triy @tombreit 
Hi, can you give it a spin and confirm it's fixed?
Cheers

**Comment by tombreit** [comment]
I'm sorry, but I can't replicate this right now (I can not even trigger my bug reported above) .

**Comment by dim1triy** [comment]
this fix is worked! Thanks
