### ISSUE TITLE
Support for wagtail snippets?

### ISSUE THREAD

**Issue by AWinterman** [infoportugal/wagtail-modeltranslation#267]
I'm trying to to create a [snippet](http://docs.wagtail.io/en/v2.1.1/topics/snippets.html) for a super simple model:

```
@register_snippet
class Link(models.Model):
    url = models.CharField(max_length=255, null=True, blank=True)
    text = models.CharField(max_length=255, null=True, blank=True)
```

I want to translate the text field: 

```
@register(Link)
class OrgSplashTR(TranslationOptions):
    fields = (
        'text',
    )

```
but when I try to run makemigrations, I get an error:

```
Traceback (most recent call last):
  File "./manage.py", line 24, in <module>
    main()
  File "./manage.py", line 20, in main
    execute_from_command_line(sys.argv)
  File "/Users/andrewwinterman/mmenv/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/Users/andrewwinterman/mmenv/lib/python3.7/site-packages/django/core/management/__init__.py", line 357, in execute
    django.setup()
  File "/Users/andrewwinterman/mmenv/lib/python3.7/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/andrewwinterman/mmenv/lib/python3.7/site-packages/django/apps/registry.py", line 122, in populate
    app_config.ready()
  File "/Users/andrewwinterman/mmenv/lib/python3.7/site-packages/wagtail_modeltranslation/apps.py", line 34, in ready
    patch_wagtail_models()
  File "/Users/andrewwinterman/mmenv/lib/python3.7/site-packages/wagtail_modeltranslation/patch_wagtailadmin.py", line 572, in patch_wagtail_models
    WagtailTranslator(model_class)
  File "/Users/andrewwinterman/mmenv/lib/python3.7/site-packages/wagtail_modeltranslation/patch_wagtailadmin.py", line 68, in __init__
    self._patch_other_models(model)
  File "/Users/andrewwinterman/mmenv/lib/python3.7/site-packages/wagtail_modeltranslation/patch_wagtailadmin.py", line 144, in _patch_other_models
    SNIPPET_EDIT_HANDLERS[model] = edit_handler.bind_to_model(model)
AttributeError: 'ObjectList' object has no attribute 'bind_to_model'
```

Is there some magic invocation I missed to make snippets work? Or are they unsupported by wagtail-modeltranslation?

**Comment by AWinterman** [comment]
A more careful reading of the wagtail docs revealed this to be an issue with a foreign key relationship (not listed).

Closing.
