### ISSUE TITLE
Unknown field(s) (search_description_en, seo_title_pt, title_pt, slug_en, slug_pt, title_en, search_description_pt, seo_title_en) specified for HomePage

### ISSUE THREAD

**Issue by flakesrc** [infoportugal/wagtail-modeltranslation#277]
The ./manage.py raise this error: Unknown field(s) (search_description_en, seo_title_pt, title_pt, slug_en, slug_pt, title_en, search_description_pt, seo_title_en) specified for HomePage

i installed the app with pipenv
```
pipenv install wagtail-modeltranslation
```
the middleware order:
```
    "django.contrib.sessions.middleware.SessionMiddleware",
    'django.middleware.locale.LocaleMiddleware',
    "django.middleware.common.CommonMiddleware",
```
languages:
```
LANGUAGE_CODE = "pt-br"
TIME_ZONE = "UTC"
USE_I18N = True
USE_L10N = True
USE_TZ = True
LANGUAGES = (
    ('pt', _('Portuguese')),
    ('en', _('English')),
)
```
the translation.py location:
```
git:(develop*) ls config                            
asgi.py  endpoints.py  __init__.py  __pycache__  settings  urls.py  wsgi.py
git:(develop*) ls config/settings
base.py  dev.py  __init__.py  prod.py  __pycache__  translation.py
```
translation.py content:
```
from modeltranslation.translator import TranslationOptions
from modeltranslation.decorators import register
from blog.posts.models import BlogPage


@register(BlogPage)
class BlogPageTR(TranslationOptions):
    fields = ('body', 'title')
```
complete traceback:
```
geeknoon_server git:(develop*) ./manage.py check
Traceback (most recent call last):
  File "./manage.py", line 20, in <module>
    main()
  File "./manage.py", line 16, in main
    execute_from_command_line(sys.argv)
  File "/home/marcos/.local/share/virtualenvs/geeknoon.com_server-yF2TReOh/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/home/marcos/.local/share/virtualenvs/geeknoon.com_server-yF2TReOh/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/marcos/.local/share/virtualenvs/geeknoon.com_server-yF2TReOh/lib/python3.8/site-packages/django/core/management/base.py", line 328, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/marcos/.local/share/virtualenvs/geeknoon.com_server-yF2TReOh/lib/python3.8/site-packages/django/core/management/base.py", line 369, in execute
    output = self.handle(*args, **options)
  File "/home/marcos/.local/share/virtualenvs/geeknoon.com_server-yF2TReOh/lib/python3.8/site-packages/django/core/management/commands/check.py", line 59, in handle
    self.check(
  File "/home/marcos/.local/share/virtualenvs/geeknoon.com_server-yF2TReOh/lib/python3.8/site-packages/django/core/management/base.py", line 392, in check
    all_issues = self._run_checks(
  File "/home/marcos/.local/share/virtualenvs/geeknoon.com_server-yF2TReOh/lib/python3.8/site-packages/django/core/management/base.py", line 382, in _run_checks
    return checks.run_checks(**kwargs)
  File "/home/marcos/.local/share/virtualenvs/geeknoon.com_server-yF2TReOh/lib/python3.8/site-packages/django/core/checks/registry.py", line 72, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/marcos/.local/share/virtualenvs/geeknoon.com_server-yF2TReOh/lib/python3.8/site-packages/wagtail/admin/checks.py", line 63, in get_form_class_check
    if not issubclass(edit_handler.get_form_class(), WagtailAdminPageForm):
  File "/home/marcos/.local/share/virtualenvs/geeknoon.com_server-yF2TReOh/lib/python3.8/site-packages/wagtail/admin/edit_handlers.py", line 350, in get_form_class
    return get_form_for_model(
  File "/home/marcos/.local/share/virtualenvs/geeknoon.com_server-yF2TReOh/lib/python3.8/site-packages/wagtail/admin/edit_handlers.py", line 62, in get_form_for_model
    return metaclass(class_name, (form_class,), form_class_attrs)
  File "/home/marcos/.local/share/virtualenvs/geeknoon.com_server-yF2TReOh/lib/python3.8/site-packages/wagtail/admin/forms/models.py", line 66, in __new__
    new_class = super(WagtailAdminModelFormMetaclass, cls).__new__(cls, name, bases, attrs)
  File "/home/marcos/.local/share/virtualenvs/geeknoon.com_server-yF2TReOh/lib/python3.8/site-packages/modelcluster/forms.py", line 234, in __new__
    new_class = super(ClusterFormMetaclass, cls).__new__(cls, name, bases, attrs)
  File "/home/marcos/.local/share/virtualenvs/geeknoon.com_server-yF2TReOh/lib/python3.8/site-packages/django/forms/models.py", line 267, in __new__
    raise FieldError(message)
django.core.exceptions.FieldError: Unknown field(s) (search_description_en, seo_title_pt, title_pt, slug_en, slug_pt, title_en, search_description_pt, seo_title_en) specified for HomePage
```

**Comment by suxilog** [comment]
you can check this link, already talked about this, I follow this link solved same problem as you posted. Add translation.py to every app, beside the models.py. good luck.
https://github.com/infoportugal/wagtail-modeltranslation/issues/230

**Comment by DiogoMarques29** [comment]
You need to register for translation all subclasses of Page.
Cheers

**Comment by vbroskas** [comment]
Can anyone(@suxilog @DiogoMarques29 ) clarify what you mean by "register for translation all subclasses of Page"? I'm getting the same error as @flakesrc. I have added a `translation.py` in the root directory of all my apps that contain a `models.py` (even those apps that require no translation). Here is an example of my `translation.py` in an app that doesn't need any translation:
```
from .models import ServiceDetails, ServicesPage
from modeltranslation.translator import TranslationOptions
from modeltranslation.decorators import register


@register(ServiceDetails)
class ServiceDetailsTR(TranslationOptions):
    fields = (

    )


@register(ServicesPage)
class ServiceDetailsTR(TranslationOptions):
    fields = (

    )
```

And here is my `translation.py` for the one page I **do need** translation (only for ProgramDetails, don't need it for ProgramsPage):
```
from .models import ProgramDetails, ProgramsPage
from modeltranslation.translator import TranslationOptions
from modeltranslation.decorators import register


@register(ProgramDetails)
class ProgramDetailsTR(TranslationOptions):
    fields = (
        'program_name',
        'program_description',
    )


@register(ProgramsPage)
class ProgramsPageTR(TranslationOptions):
    fields = (

    )
```

here is the error I'm getting: 

> django.core.exceptions.FieldError: Unknown field(s) (slug_fa, seo_title_vi, slug_vi, seo_title_fa, search_description_en, slug_zh_hans, seo_title_zh_hans, slug_en, slug_ja, search_description_vi, seo_title_ja, seo_title_zh_hant, search_description_zh_hans, search_description_ja, slug_zh_hant, seo_title_en, search_description_zh_hant, search_description_fa) specified for GroupPage

I know I'm being very stupid right now so I appreciate any help you can provide, thanks!

**Comment by vbroskas** [comment]
Figured it out, `GroupPage` was buried down in a calendar plugin I'm using!

**Comment by rokondo** [comment]
The following codes registering all not registered models without any field (or whatever you want):
```
from .models import *
from modeltranslation.translator import translator,TranslationOptions
from modeltranslation.decorators import register

@register(BlogPage)
class BlogPageTR(TranslationOptions):
    fields = (
        'intro',
    )

import django.apps
models={}
for model in django.apps.apps.get_models():
	if model not in translator.get_registered_models():
		try:
		    name = model.__name__
		    models[name] = type(name+"TR", 
		              (TranslationOptions,), 
		              {"fields":()})
		    translator.register(model,models[name])
		except:
			print('some problem registering '+name)
```
