### ISSUE TITLE
Using Modeltranslation with calendar plugin pages

### ISSUE THREAD

**Issue by vbroskas** [infoportugal/wagtail-modeltranslation#289]
I'm having an issue with using modeltranslation in conjunction with the wagtail joyous calendar plugin. Because many parts of the calendar inherit from the wagtail `Page` class, I need to create an app which extends the models from Joyous, and then add my `translation.py` file which registers TranslationOptions for a handful of the pages built into the calendar. 

When I have modeltranslations deactivated the calendar works fine, however when I activate it, I'm having some issues. In my translation.py , if I register for:
```
@register(CalendarPage)
class CalendarPageTR(TranslationOptions):
    fields = (

    )
```
I'm unable to `makemigrations/migrate` and I get errors relating to fields from a class that calendar builds from:
```
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/lo/Code/clients/nmafc/venv/lib/python3.6/site-packages/django/utils/autoreload.py", line 54, in wrapper
    fn(*args, **kwargs)
  File "/home/lo/Code/clients/nmafc/venv/lib/python3.6/site-packages/django/core/management/commands/runserver.py", line 117, in inner_run
    self.check(display_num_errors=True)
  File "/home/lo/Code/clients/nmafc/venv/lib/python3.6/site-packages/django/core/management/base.py", line 390, in check
    include_deployment_checks=include_deployment_checks,
  File "/home/lo/Code/clients/nmafc/venv/lib/python3.6/site-packages/django/core/management/base.py", line 377, in _run_checks
    return checks.run_checks(**kwargs)
  File "/home/lo/Code/clients/nmafc/venv/lib/python3.6/site-packages/django/core/checks/registry.py", line 72, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/lo/Code/clients/nmafc/venv/lib/python3.6/site-packages/wagtail/admin/checks.py", line 63, in get_form_class_check
    if not issubclass(edit_handler.get_form_class(), WagtailAdminPageForm):
  File "/home/lo/Code/clients/nmafc/venv/lib/python3.6/site-packages/wagtail/admin/edit_handlers.py", line 369, in get_form_class
    widgets=self.widget_overrides())
  File "/home/lo/Code/clients/nmafc/venv/lib/python3.6/site-packages/wagtail/admin/edit_handlers.py", line 64, in get_form_for_model
    return metaclass(class_name, (form_class,), form_class_attrs)
  File "/home/lo/Code/clients/nmafc/venv/lib/python3.6/site-packages/wagtail/admin/forms/models.py", line 66, in __new__
    new_class = super(WagtailAdminModelFormMetaclass, cls).__new__(cls, name, bases, attrs)
  File "/home/lo/Code/clients/nmafc/venv/lib/python3.6/site-packages/modelcluster/forms.py", line 245, in __new__
    new_class = super(ClusterFormMetaclass, cls).__new__(cls, name, bases, attrs)
  File "/home/lo/Code/clients/nmafc/venv/lib/python3.6/site-packages/django/forms/models.py", line 266, in __new__
    raise FieldError(message)
django.core.exceptions.FieldError: Unknown field(s) (utc2local, upload) specified for CalendarPage
```
(I've tried also including the class that CalendarPage extends but that just leads to other errors)
If I don't register for CalendarPage, I'm able to makemigrations/migrate/update_translation_fields, however when I go into the dashboard and try to publish a calendar page, I get a validation error saying that the title field for a calendar page cannot be blank even though I have it filled out and I get this:
```
Traceback (most recent call last):
  File "/home/lo/Code/clients/nmafc/venv/lib/python3.6/site-packages/django/template/base.py", line 850, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [mode] in [{'True': True, 'False': False, 'None': None}, {'csrf_token': <SimpleLazyObject: 'v3lFjCxgbqFnIRgbqKSuiAduj9Z3TI5N88JqnqRF0w$..............
"POST /admin/pages/add/joyous/calendarpage/3/ HTTP/1.1" 200 37660
```
Has anyone else had a similar issue to this where you have to either register translations for another plugin, or you're unable to publish a page due to validation errors? I'm assuming I'm being stupid and missing something really obvious...

**Comment by vbroskas** [comment]
I just went ahead and tried to remove my custom `events` app that was used to extend the Joyous calendar, however after deleting the app, and removing it from my `INSTALLED_APPS`, now when I try to `makemigrations` or `update_translation_fields` I get the error:

```
django.core.exceptions.FieldError: Unknown field(s) (search_description_zh_hant, search_description_zh_hans, slug_zh_hant, slug_ja, seo_title_vi, seo_title_en, seo_title_fa, seo_title_ja, slug_ko, slug_vi, seo_title_hi, search_description_hi, seo_title_zh_hant, seo_title_zh_hans, search_description_fa, search_description_vi, slug_fa, search_description_ja, search_description_ko, seo_title_ko, search_description_en, slug_hi, slug_en, slug_zh_hans) specified for GroupPage
```
`GroupPage` is one of the wagtail page models in the Joyous Calendar. How do I remove an app from my project and not have Modeltranslations keep trying to look for it?

**Comment by vbroskas** [comment]
@linuxsoftware the creator of Joyous Calendar implemented a temporary work-around to this issue. Please see here: https://github.com/linuxsoftware/ls.joyous/issues/33#issue-676378677
