### ISSUE TITLE
WagtailTranslator overwrites base_form_class

### ISSUE THREAD

**Issue by linuxsoftware** [infoportugal/wagtail-modeltranslation#291]
Thanks for the work on wagtail-modeltranslation.

It is surprise to me (and I think other developers) that a model with a base_form_class has this overwritten without any regard to its previous value.

If WagtailTranslator cannot work any other way, then it would be good if this could be clearly documented.

The example below illustrates the problem.

My example model is taken straight from the Wagtail documentation:
https://docs.wagtail.io/en/stable/advanced_topics/customisation/page_editing_interface.html#customising-generated-forms

```
from django import forms
from django.db import models
import geocoder
from wagtail.admin.edit_handlers import FieldPanel
from wagtail.admin.forms import WagtailAdminPageForm
from wagtail.core.models import Page


class EventPageForm(WagtailAdminPageForm):
    address = forms.CharField()

    def clean(self):
        cleaned_data = super().clean()

        # Make sure that the event starts before it ends
        start_date = cleaned_data['start_date']
        end_date = cleaned_data['end_date']
        if start_date and end_date and start_date > end_date:
            self.add_error('end_date', 'The end date must be after the start date')

        return cleaned_data

    def save(self, commit=True):
        page = super().save(commit=False)

        # Update the duration field from the submitted dates
        page.duration = (page.end_date - page.start_date).days

        # Fetch the location by geocoding the address
        page.location = geocoder.arcgis(self.cleaned_data['address'])

        if commit:
            page.save()
        return page


class EventPage(Page):
    start_date = models.DateField()
    end_date = models.DateField()
    duration = models.IntegerField()
    location = models.CharField(max_length=255)

    content_panels = [
        FieldPanel('title'),
        FieldPanel('start_date'),
        FieldPanel('end_date'),
        FieldPanel('address'),
    ]
    base_form_class = EventPageForm
```

My translation.py file
```
from wagtail_modeltranslation.translation import TranslationOptions
from modeltranslation.decorators import register
from .models import EventPage

@register(EventPage)
class EventTR(TranslationOptions):
    fields = (
    )
```

The stack trace
```
$ ./manage.py migrate
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/me/env/example/lib64/python3.7/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/home/me/env/example/lib64/python3.7/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/me/env/example/lib64/python3.7/site-packages/django/core/management/base.py", line 328, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/me/env/example/lib64/python3.7/site-packages/django/core/management/base.py", line 366, in execute
    self.check()
  File "/home/me/env/example/lib64/python3.7/site-packages/django/core/management/base.py", line 395, in check
    include_deployment_checks=include_deployment_checks,
  File "/home/me/env/example/lib64/python3.7/site-packages/django/core/management/commands/migrate.py", line 64, in _run_checks
    issues.extend(super()._run_checks(**kwargs))
  File "/home/me/env/example/lib64/python3.7/site-packages/django/core/management/base.py", line 382, in _run_checks
    return checks.run_checks(**kwargs)
  File "/home/me/env/example/lib64/python3.7/site-packages/django/core/checks/registry.py", line 72, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/me/env/example/lib64/python3.7/site-packages/wagtail/admin/checks.py", line 63, in get_form_class_check
    if not issubclass(edit_handler.get_form_class(), WagtailAdminPageForm):
  File "/home/me/env/example/lib64/python3.7/site-packages/wagtail/admin/edit_handlers.py", line 355, in get_form_class
    widgets=self.widget_overrides())
  File "/home/me/env/example/lib64/python3.7/site-packages/wagtail/admin/edit_handlers.py", line 62, in get_form_for_model
    return metaclass(class_name, (form_class,), form_class_attrs)
  File "/home/me/env/example/lib64/python3.7/site-packages/wagtail/admin/forms/models.py", line 75, in __new__
    new_class = super(WagtailAdminModelFormMetaclass, cls).__new__(cls, name, bases, attrs)
  File "/home/me/env/example/lib64/python3.7/site-packages/modelcluster/forms.py", line 234, in __new__
    new_class = super(ClusterFormMetaclass, cls).__new__(cls, name, bases, attrs)
  File "/home/me/env/example/lib64/python3.7/site-packages/django/forms/models.py", line 267, in __new__
    raise FieldError(message)
django.core.exceptions.FieldError: Unknown field(s) (address) specified for EventPage
```

And even if the address FieldPanel is removed to get past that error, there are further problems as the EventPageForm clean and save methods are not called.

**Comment by DiogoMarques29** [comment]
A fix has been made in v0.10.14
