### ISSUE TITLE
modeltranslation.translator.DescendantRegistered: Model "Page" cannot be registered after its subclass "LocationPage"

### ISSUE THREAD

**Issue by mcosti** [infoportugal/wagtail-modeltranslation#374]
Hey there, thanks for this great package.

I am using 
```
Django==4.1.0
wagtail==4.1.1
wagtail-modeltranslation==0.13rc3
```

And 70% of the times I change a file, it raises this error (due to auto-reload):

```
2023-01-02T18:28:26.747528466Z {"event": "Watching for file changes with StatReloader"}
2023-01-02T18:28:26.748252216Z Exception in thread django-main-thread:
2023-01-02T18:28:26.748270050Z Traceback (most recent call last):
2023-01-02T18:28:26.748273883Z   File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
2023-01-02T18:28:26.748362341Z     self.run()
2023-01-02T18:28:26.748404341Z   File "/usr/lib/python3.10/threading.py", line 953, in run
2023-01-02T18:28:26.748483675Z     self._target(*self._args, **self._kwargs)
2023-01-02T18:28:26.748494883Z   File "/usr/local/lib/python3.10/dist-packages/django/utils/autoreload.py", line 64, in wrapper
2023-01-02T18:28:26.748498300Z     fn(*args, **kwargs)
2023-01-02T18:28:26.748500466Z   File "/usr/local/lib/python3.10/dist-packages/django/core/management/commands/runserver.py", line 125, in inner_run
2023-01-02T18:28:26.748712508Z     autoreload.raise_last_exception()
2023-01-02T18:28:26.748728591Z   File "/usr/local/lib/python3.10/dist-packages/django/utils/autoreload.py", line 87, in raise_last_exception
2023-01-02T18:28:26.748748341Z     raise _exception[1]
2023-01-02T18:28:26.748751050Z   File "/usr/local/lib/python3.10/dist-packages/django/core/management/__init__.py", line 398, in execute
2023-01-02T18:28:26.748753383Z     autoreload.check_errors(django.setup)()
2023-01-02T18:28:26.748755466Z   File "/usr/local/lib/python3.10/dist-packages/django/utils/autoreload.py", line 64, in wrapper
2023-01-02T18:28:26.748757508Z     fn(*args, **kwargs)
2023-01-02T18:28:26.748759258Z   File "/usr/local/lib/python3.10/dist-packages/django/__init__.py", line 24, in setup
2023-01-02T18:28:26.748898508Z     apps.populate(settings.INSTALLED_APPS)
2023-01-02T18:28:26.748909008Z   File "/usr/local/lib/python3.10/dist-packages/django/apps/registry.py", line 124, in populate
2023-01-02T18:28:26.748912133Z     app_config.ready()
2023-01-02T18:28:26.748913966Z   File "/usr/local/lib/python3.10/dist-packages/wagtail_modeltranslation/apps.py", line 28, in ready
2023-01-02T18:28:26.748926716Z     handle_translation_registrations()
2023-01-02T18:28:26.748939716Z   File "/usr/local/lib/python3.10/dist-packages/modeltranslation/models.py", line 78, in handle_translation_registrations
2023-01-02T18:28:26.748990341Z     autodiscover()
2023-01-02T18:28:26.748993550Z   File "/usr/local/lib/python3.10/dist-packages/modeltranslation/models.py", line 27, in autodiscover
2023-01-02T18:28:26.749052341Z     import_module(module)
2023-01-02T18:28:26.749063466Z   File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
2023-01-02T18:28:26.749066633Z     return _bootstrap._gcd_import(name[level:], package, level)
2023-01-02T18:28:26.749068925Z   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
2023-01-02T18:28:26.749632800Z   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
2023-01-02T18:28:26.750003341Z   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
2023-01-02T18:28:26.750388550Z   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
2023-01-02T18:28:26.750768758Z   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
2023-01-02T18:28:26.751218675Z   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
2023-01-02T18:28:26.751611508Z   File "/usr/local/lib/python3.10/dist-packages/wagtail_modeltranslation/translation.py", line 9, in <module>
2023-01-02T18:28:26.751627216Z     class PageTR(TranslationOptions):
2023-01-02T18:28:26.751641133Z   File "/usr/local/lib/python3.10/dist-packages/modeltranslation/decorators.py", line 20, in wrapper
2023-01-02T18:28:26.751644341Z     translator.register(model_or_iterable, opts_class, **options)
2023-01-02T18:28:26.751647091Z   File "/usr/local/lib/python3.10/dist-packages/modeltranslation/translator.py", line 476, in register
2023-01-02T18:28:26.751787716Z     raise DescendantRegistered(
2023-01-02T18:28:26.751801050Z modeltranslation.translator.DescendantRegistered: Model "Page" cannot be registered after its subclass "LocationPage"
```

My INSTALLED_APPS looks like this:

```python
    "wagtail.contrib.forms",
    "wagtail.contrib.redirects",
    "wagtail.documents",
    "wagtail.embeds",
    "wagtail.sites",
    "wagtail.users",
    "wagtail.snippets",
    "wagtail.images",
    "wagtail.search",
    "wagtail.admin",
    "wagtail",
    "wagtailautocomplete",
    "wagtail_modeltranslation",
    "wagtail_modeltranslation.makemigrations",
    "wagtail_modeltranslation.migrate",
     ....
    "my_custom_apps"
```
Sometimes it also happens when I'm freshly starting the docker image, so this could be a real problem on production.
Is this something you could help me with?

Thanks

**Comment by mcosti** [comment]
I just had this idea of doing it like this, but unfortunately it didn't work

```python
from django.apps import AppConfig
from modeltranslation.translator import translator

from cms.translation import LocationPageTR


class CmsConfig(AppConfig):
    default_auto_field = "django.db.models.BigAutoField"
    name = "cms"

    def ready(self):
        from cms.models import LocationPage
        translator.register(LocationPage, LocationPageTR)
```

**Comment by mcosti** [comment]
Okay... this hack works, but I would still really appreciate if we can find a proper fix to it.

```python
from django.apps import AppConfig
from modeltranslation.translator import AlreadyRegistered, translator

from cms.translation import LocationPageTR


class CmsConfig(AppConfig):
    default_auto_field = "django.db.models.BigAutoField"
    name = "cms"

    def ready(self):
        register_translators()


def register_translators():
    from cms.models import LocationPage
    from wagtail.models import Page
    from wagtail_modeltranslation.translation import PageTR

    try:
        translator.register(Page, PageTR)  # hack while the package maintainer fixes the issue
    except AlreadyRegistered:
        pass

    translator.register(LocationPage, LocationPageTR)
```

**Comment by JeremyAube** [comment]
in `INSTALLED_APPS` you should have this:
```
"wagtail_modeltranslation",
"wagtail_modeltranslation.makemigrations",
"wagtail_modeltranslation.migrate",
```

**before** any app you want to translate (before the `cms` app in your case)

**Comment by DiogoMarques29** [comment]
Thank you @JeremyAube 
@mcosti have you tried what @JeremyAube suggested? If it's correct, we should add a note to the documentation.

**Comment by mcosti** [comment]
Hey guys, thanks for answering. If you notice in my first message, I showed my installed apps and it's according to the order you provided, so that was not the fix

**Comment by Alexandre27** [comment]
Hi @mcosti,

I tried to emulate the error that you're finding to no avail. I don't know the exact environment and implementation you're using but tried using an existing project that I have, forcing the autoreload to trigger on demand and logging the order in that models were registered.
After 1000+ tries, I never got the `DescendantRegistered` error, and the order was always the same. As @DiogoMarques29 and @JeremyAube stated, at first look, the problem seems to be that for some reason the app order is not being respected and your app `cms` is being loaded before the `Page` is registered in that 70% of the time.
Without being able to replicate the error, there's not much that I can do to help, so if you can, create a repo with a sample project where you get the error so I can debug what's happening.
